export const meta = {
  slug: 'triangle-led-god-rays',
  title: 'Triangle LED God Rays',
  description: 'A multipass WebGPU port of the Vercel homepage triangle hero with cascaded radiance, bloom, and additive god rays.',
  thumb: { warmupFrames: 60, dt: 1 / 60 },
  files: [
    'example.ts',
    'renderer.ts',
    'led-buffer.ts',
    'settings.ts',
    'shaders/light-sources.wgsl',
    'shaders/cascade-build.wgsl',
    'shaders/cascade-merge.wgsl',
    'shaders/cascade-utils.wgsl',
    'shaders/color-utils.wgsl',
    'shaders/floor-noise.wgsl',
    'shaders/geometry.wgsl',
    'shaders/hash.wgsl',
    'shaders/radiance-field.wgsl',
    'shaders/main-scene-floor.wgsl',
    'shaders/main-scene-triangle.wgsl',
    'shaders/main-scene-god-rays.wgsl',
    'shaders/ray-aabb.wgsl',
    'shaders/ray-segment.wgsl',
    'shaders/sample-dir.wgsl',
    'shaders/bloom.wgsl',
    'shaders/composite.wgsl',
  ],
} as const;
