export const meta = {
  slug: 'liquid-layout',
  title: 'Liquid Layout',
  description:
    'Drag to reorder, shuffle and filter eight DOM cards with Motion while vgpu renders them as one refracting water-glass field that necks between neighbours.',
  tags: [
    'motion',
    'liquid',
    'refraction',
    'layout',
    'drag',
    'glass',
    'sdf',
    'chromatic-aberration',
    'bloom',
    'hdr',
    'post-processing',
    'animation',
  ],
  capabilities: [
    'webgpu',
    'fragment-shader',
    'multi-pass',
    'instanced-rendering',
    'render-targets',
    'hdr',
    'textures',
    'external-ticker',
    'dom-overlay',
    'pointer-input',
    'controls',
    'select-control',
    'checkbox-controls',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: {
    warmupFrames: 3,
    dt: 1 / 60,
    time: 4,
  },
  files: [
    'index.tsx',
    'liquid-cards.tsx',
    'layout-store.ts',
    'cards.ts',
    'renderer.ts',
    'liquid-dynamics.ts',
    'liquid-pipeline.ts',
    'backdrop.wgsl',
    'field.wgsl',
    'shade.wgsl',
    'bubbles.wgsl',
    'bright.wgsl',
    'blur.wgsl',
    'composite.wgsl',
  ],
} as const;
