export const meta = {
  slug: 'liquid-layout',
  title: 'Liquid Layout',
  description:
    'Motion lays out eight real DOM cards and vgpu pours them as liquid glass. Shuffles and filters are Motion layout animations, opening a card is a shared layoutId hand-off to a panel, and dragged cards snap back on a spring. Every frame, inside Motion’s own frameloop, the renderer reads each card’s rect and velocity and turns them into a smooth-union distance field: moving cards stretch tethers and shed droplets, then the field is lit as refracting, dispersive glass over an aurora backdrop with caustics, bloom and ACES tone mapping. Drag a card, click to open, or let the autoplay run.',
  tags: [
    'motion',
    'liquid',
    'refraction',
    'layout',
    'drag',
    'glass',
    'sdf',
    'chromatic-aberration',
    'bloom',
    'hdr',
    'post-processing',
    'animation',
  ],
  capabilities: [
    'webgpu',
    'fragment-shader',
    'multi-pass',
    'render-targets',
    'hdr',
    'textures',
    'external-ticker',
    'dom-overlay',
    'pointer-input',
    'controls',
    'select-control',
    'checkbox-controls',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: {
    warmupFrames: 60,
    dt: 1 / 60,
    time: 4,
  },
  files: [
    'index.tsx',
    'liquid-cards.tsx',
    'layout-store.ts',
    'cards.ts',
    'renderer.ts',
    'liquid-dynamics.ts',
    'liquid-pipeline.ts',
    'backdrop.wgsl',
    'field.wgsl',
    'shade.wgsl',
    'bright.wgsl',
    'blur.wgsl',
    'composite.wgsl',
  ],
} as const;
