#!/usr/bin/env python3
"""Captures the depth example's deterministic thumbnail fixture.

The docs thumbnails must render identically on any machine, in Node, with no
GPU model inference and no network. That means the depth field they draw has to
be committed. This script produces it by running the *same* model bytes the
browser loads, through ONNX Runtime's CPU execution provider, on the committed
source image.

The result is real model output, not synthetic data. It is not, however, proof
of browser interop: the CPU EP and the WebGPU EP are different backends, and
Pillow's resampling is not Canvas2D's. The thumbnail validates the visualizer;
the WebGPU path is proven separately by the real-GPU gate.

Usage:
  .venv/bin/python make-golden-depth.py            regenerate the fixture
  .venv/bin/python make-golden-depth.py --check    fail if the fixture is stale
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import sys
from pathlib import Path

import numpy as np
import onnxruntime as ort
from PIL import Image

REPO = Path(__file__).resolve().parents[3]
MODEL = REPO / "apps/docs/public/models/depth/fastdepth-320x256.onnx"
SOURCE = REPO / "apps/docs/public/examples/depth-estimation/source.jpg"
OUT = REPO / "apps/docs/examples/depth-estimation/golden-depth.generated.ts"

MODEL_ID = "fastdepth-320x256"
WIDTH, HEIGHT = 320, 256
INPUT_NAME, OUTPUT_NAME = "input.1", "424"
# Quantization ceiling in metres. FastDepth's indoor range tops out near 8 m, so
# 16 m leaves headroom while keeping the step at 0.24 mm.
SCALE_METERS = 16.0


def cover_crop(image: Image.Image, width: int, height: int) -> Image.Image:
    """Mirror depth-estimation/renderer.ts: coverCrop, then resize."""
    target = width / height
    sw, sh = image.size
    if sw / sh > target:
        sw = round(sh * target)
    else:
        sh = round(sw / target)
    left = round((image.size[0] - sw) / 2)
    top = round((image.size[1] - sh) / 2)
    return image.crop((left, top, left + sw, top + sh)).resize((width, height), Image.LANCZOS)


def render() -> str:
    for path in (MODEL, SOURCE):
        if not path.exists():
            sys.exit(f"missing {path} (run `pnpm --filter docs depth:models`)")

    model_sha = hashlib.sha256(MODEL.read_bytes()).hexdigest()
    source_sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()

    crop = cover_crop(Image.open(SOURCE).convert("RGB"), WIDTH, HEIGHT)
    # rgb/255, NCHW. FastDepth does not use ImageNet statistics.
    rgb = np.asarray(crop, dtype=np.float32) / 255.0
    nchw = np.transpose(rgb, (2, 0, 1))[None, ...].copy()

    session = ort.InferenceSession(str(MODEL), providers=["CPUExecutionProvider"])
    depth = session.run([OUTPUT_NAME], {INPUT_NAME: nchw})[0]
    if depth.shape != (1, 1, HEIGHT, WIDTH):
        sys.exit(f"unexpected output shape {depth.shape}")

    flat = np.asarray(depth, dtype=np.float32).reshape(-1)
    if not np.isfinite(flat).all():
        sys.exit("model produced non-finite depth")

    quantized = np.clip(flat / SCALE_METERS, 0.0, 1.0)
    encoded = np.round(quantized * 65535.0).astype("<u2")
    payload = base64.b64encode(encoded.tobytes()).decode("ascii")
    # Round-trip the way the decoder will, so the committed statistics describe
    # what the shader actually receives rather than the pre-quantization ideal.
    restored = encoded.astype(np.float32) / 65535.0 * SCALE_METERS

    # The colour half of the view. Committed as raw RGB rather than an encoded
    # image because the Node thumbnail path has no image decoder, and this keeps
    # the fixture a straight memcpy into the storage buffer.
    colour_payload = base64.b64encode(np.asarray(crop, dtype=np.uint8).tobytes()).decode("ascii")
    colour_wrapped = "\n".join(colour_payload[i : i + 116] for i in range(0, len(colour_payload), 116))

    wrapped = "\n".join(payload[i : i + 116] for i in range(0, len(payload), 116))
    lines = [
        "// GENERATED by tools/models/depth-candidates/make-golden-depth.py -- do not edit.",
        "//",
        f"// {MODEL_ID} run through the ONNX Runtime CPU EP on the committed source",
        "// image, quantized to unsigned 16-bit over a fixed metric range. Feeding the",
        "// thumbnail real model output is what keeps it honest; see fixtures.ts for the",
        "// decoder and PROVENANCE.md for exactly how this was captured.",
        "//",
        "// The payloads are arrays joined at import, not `+` chains. A concatenation of",
        "// N wrapped lines is an N-deep binary-expression node, and `next build` walks",
        "// it recursively: at 2,824 terms its type-check worker died with `RangeError:",
        "// Maximum call stack size exceeded`, while `tsc --noEmit` passed because it",
        "// never runs the emit pass that does the walking. An array literal is flat.",
        "",
        f"export const GOLDEN_MODEL_SHA256 = '{model_sha}';",
        f"export const GOLDEN_SOURCE_SHA256 = '{source_sha}';",
        f"export const GOLDEN_SCALE_METERS = {SCALE_METERS};",
        f"export const GOLDEN_WIDTH = {WIDTH};",
        f"export const GOLDEN_HEIGHT = {HEIGHT};",
        "/** Statistics of the decoded field, in metres. */",
        "export const GOLDEN_STATS = {",
        f"  min: {float(restored.min()):.6f},",
        f"  max: {float(restored.max()):.6f},",
        f"  mean: {float(restored.mean()):.6f},",
        "} as const;",
        "/** Row-major RGB8 of the same crop, base64. */",
        "export const GOLDEN_COLOUR_BASE64 = [",
        *[f"  '{line}'," for line in colour_wrapped.split("\n")],
        "].join('');",
        "/** Row-major u16 depth, little endian, base64. */",
        "export const GOLDEN_DEPTH_BASE64 = [",
        *[f"  '{line}'," for line in wrapped.split("\n")],
        "].join('');",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != generated:
            sys.exit(
                f"{OUT.relative_to(REPO)} is stale.\n"
                "Run tools/models/depth-candidates/make-golden-depth.py to regenerate it."
            )
        print(f"{OUT.relative_to(REPO)} is up to date.")
        return

    OUT.write_text(generated)
    print(f"wrote {OUT.relative_to(REPO)} ({len(generated)} bytes)")


if __name__ == "__main__":
    main()
