export const meta = {
  slug: 'triangle-led-front',
  title: 'Triangle LED Hero',
  description: 'Analytic edge-glow triangle with LED emitters, floor radiance, and interactive color deploy.',
  thumb: { warmupFrames: 90, dt: 1 / 60 },
  files: [
    'example.ts',
    'renderer.ts',
    'light-sources-raw.ts',
    'light-sources-pass.ts',
    'led-buffer.ts',
    'settings.ts',
    'hero-frame-state.ts',
    'direct-triangle-raycast.ts',
    'value-noise.ts',
    'triangle-hit.ts',
    'sim-sizing.ts',
    'shaders/light-sources.wgsl',
    'shaders/led-emitters.wgsl',
    'shaders/direct-triangle-raycast.wgsl',
    'shaders/floor-noise.wgsl',
    'shaders/color-utils.wgsl',
    'shaders/geometry.wgsl',
    'shaders/floor-falloff.wgsl',
    'shaders/hash.wgsl',
    'shaders/themes/dark/main-scene-floor.wgsl',
    'shaders/themes/light/main-scene-floor.wgsl',
  ],
} as const;
