export const meta = {
  slug: 'triangle-led-front',
  title: 'Triangle LED Hero',
  description: 'Analytic edge-glow triangle with LED emitters, floor radiance, and interactive color deploy. Canvas-scoped pointer input drives the lighting while a lil-gui selector chooses highlighted edges.',
  tags: ['triangle', 'led', 'raycasting', 'lighting'],
  capabilities: ['webgpu', 'select-control', 'pointer-input', 'multi-pass', 'continuous-rendering', 'responsive-canvas'],
  thumb: { warmupFrames: 90, dt: 1 / 60 },
  files: [
    'index.tsx',
    'types.ts',
    'renderer.ts',
    'scene-renderer.ts',
    'light-sources-raw.ts',
    'led-buffer.ts',
    'settings.ts',
    'hero-frame-state.ts',
    'sim-sizing.ts',
    'shaders/led-emitters.wgsl',
    'shaders/direct-triangle-raycast.wgsl',
    'shaders/floor-noise.wgsl',
    'shaders/color-utils.wgsl',
    'shaders/geometry.wgsl',
    'shaders/floor-falloff.wgsl',
    'shaders/hash.wgsl',
    'shaders/themes/dark/main-scene-floor.wgsl',
  ],
} as const;
