import type { ExampleMetaDefinition } from '../../lib/example-meta';

export const meta = {
  slug: 'prism-rainbow',
  title: 'Prism Rainbow',
  description:
    'A finite collimated beam is traced analytically through a prism with Snell refraction, Fresnel transmission and total internal reflection. Adjacent wavelength vertices become continuous additive mesh sheets, while an HDR ping-pong pipeline resolves both glass interfaces and a jittered four-level bloom pyramid before final tone mapping. An optional orbitable mirror ball and XYZ gizmo expose the analytic studio environment for visual tuning.',
  tags: ['lighting', 'raycasting', 'rendering', 'frosted-glass', 'shader'],
  capabilities: [
    'webgpu',
    'fragment-shader',
    'multi-pass',
    'render-targets',
    'textures',
    'continuous-rendering',
    'pointer-input',
    'pointer-orbit',
    'controls',
    'select-control',
    'responsive-canvas',
  ],
  thumb: {
    warmupFrames: 1,
    note: 'One deterministic render of the analytic ray bundle, continuous spectral mesh, wall and two-interface glass passes.',
  },
  files: [
    'index.tsx',
    'controls.tsx',
    'renderer.ts',
    'environment-debug.ts',
    'scene.ts',
    'camera.ts',
    'prism-mesh.ts',
    'types.ts',
    'optics.ts',
    'light-mesh.ts',
    'validation.ts',
    'scene.wgsl',
    'light.wgsl',
    'wall.wgsl',
    'copy-linear.wgsl',
    'bloom.wgsl',
    'bloom-upsample.wgsl',
    'glass-common.wgsl',
    'glass-back.wgsl',
    'glass.wgsl',
    'wireframe.wgsl',
    'environment.wgsl',
    'environment-debug.wgsl',
    'environment-debug-axes.wgsl',
    'present.wgsl',
  ],
} as const satisfies ExampleMetaDefinition;
