export const meta = {
  slug: 'marble-machine',
  title: 'Marble Machine',
  guide: '/docs/guides/scene-composition',
  description:
    'Glossy striped marbles roll down maple ramps and pile into a felt tray; cannon-es runs the physics and vgpu/scene instances draw every body.',
  tags: ['3d', 'cannon', 'physics', 'simulation', 'shadows', 'instancing'],
  capabilities: [
    'webgpu',
    'instanced-rendering',
    'render-targets',
    'multi-pass',
    'pointer-orbit',
    'pointer-input',
    'fixed-timestep',
    'controls',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: { warmupFrames: 1, dt: 1 / 60, time: 4 },
  files: [
    'index.tsx',
    'renderer.ts',
    'simulation.ts',
    'machine.ts',
    'scene.ts',
    'camera.ts',
    'input.ts',
    'controls.ts',
    'pipeline.ts',
    'common.wgsl',
    'solids.wgsl',
    'marbles.wgsl',
    'shadow.wgsl',
    'backdrop.wgsl',
    'present.wgsl',
  ],
} as const;
