import { createServer } from "node:http";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { lstat,mkdir,mkdtemp,readFile,readdir,rename,rm,symlink,writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach,expect,test } from "vitest";
import { ExamplesCache } from "../../lib/examples/cache.js";
import { assertTrustedUrl,requestBytes } from "../../lib/examples/http.js";
import { validateDiscovery,validateIndex,validatePointer } from "../../lib/examples/schema.js";
import { searchExamples } from "../../lib/examples/search.js";
import { pullExample } from "../../lib/examples/pull.js";
import { runExamples } from "../../lib/examples/run.js";
const cleanup:(()=>Promise<void>)[]=[];afterEach(async()=>{while(cleanup.length)await cleanup.pop()!()});
async function temp(prefix:string){const p=await mkdtemp(join(tmpdir(),prefix));cleanup.push(()=>rm(p,{recursive:true,force:true}));return p}
const rev="a".repeat(64),sha="b".repeat(64),origin="https://vgpu.labs.vercel.dev";

test("cache rejects symlinked root, intermediate, and leaf on reads and writes",async()=>{const base=await temp("cache-links-"),outside=await temp("cache-outside-");await symlink(outside,join(base,"root-link"));const rootLink=new ExamplesCache(join(base,"root-link"));await expect(rootLink.write(rootLink.discoveryPath(),Buffer.from("x"))).rejects.toMatchObject({code:"VGPU-EXAMPLES-FILESYSTEM"});
 const cache=new ExamplesCache(join(base,"cache"));await cache.write(cache.discoveryPath(),Buffer.from("ok"));await symlink(outside,join(cache.root,"v1"));await expect(cache.write(cache.indexPath(rev),Buffer.from("escape"))).rejects.toMatchObject({code:"VGPU-EXAMPLES-FILESYSTEM"});await rm(join(cache.root,"v1"));await mkdir(cache.revisionDir(rev),{recursive:true});await writeFile(join(outside,"object"),"outside");await symlink(join(outside,"object"),cache.indexPath(rev));await expect(cache.read(cache.indexPath(rev))).rejects.toMatchObject({code:"VGPU-EXAMPLES-FILESYSTEM"});await expect(cache.write(cache.indexPath(rev),Buffer.from("replace"))).rejects.toMatchObject({code:"VGPU-EXAMPLES-FILESYSTEM"});expect(await readFile(join(outside,"object"),"utf8")).toBe("outside")});

test("rejects 206 and unsolicited or mismatched 304",async()=>{const server=createServer((req,res)=>{if(req.url==="/partial"){res.statusCode=206;res.setHeader("content-type","application/json");return res.end("{}")}res.statusCode=304;if(req.url==="/mismatch")res.setHeader("etag",'"other"');res.end()});await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));cleanup.push(()=>new Promise<void>((r,j)=>server.close(e=>e?j(e):r())));const base=`http://127.0.0.1:${(server.address() as any).port}`,opts={limit:100,contentTypes:["application/json"]};await expect(requestBytes(`${base}/partial`,opts)).rejects.toMatchObject({code:"VGPU-EXAMPLES-NETWORK"});await expect(requestBytes(`${base}/none`,opts)).rejects.toMatchObject({code:"VGPU-EXAMPLES-NETWORK"});await expect(requestBytes(`${base}/mismatch`,{...opts,etag:'"stored"'})).rejects.toMatchObject({code:"VGPU-EXAMPLES-NETWORK"})});

test("runtime validation rejects duplicate contracts, non-URI pointer, and empty source",()=>{const contract={id:"vgpu-examples/v1",schemaSha256:sha,status:"active",minimumCliVersion:"1.0.0",indexUrl:`${origin}/api/examples/v1/latest.json`};expect(()=>validateDiscovery({protocol:"vgpu-examples",discoveryVersion:1,contracts:[contract,{...contract,status:"revoked"}]})).toThrow();expect(()=>validatePointer({schemaVersion:1,contractId:"vgpu-examples/v1",revision:rev,indexUrl:"not a uri",indexSha256:sha})).toThrow();expect(()=>validateIndex({schemaVersion:1,contractId:"vgpu-examples/v1",revision:rev,source:{repository:"",gitCommit:""},examples:[]})).toThrow()});

test("immutable URLs reject queries, fragments, and a different revision",()=>{expect(()=>assertTrustedUrl(`${origin}/examples/v1/revisions/${rev}/index.json?x=1`,origin,rev)).toThrow();expect(()=>assertTrustedUrl(`${origin}/examples/v1/revisions/${rev}/index.json#x`,origin,rev)).toThrow();expect(()=>assertTrustedUrl(`${origin}/examples/v1/revisions/${"c".repeat(64)}/index.json`,origin,rev)).toThrow()});

test("empty-token search is a pre-network structured usage error",async()=>{const index:any={examples:[]};for(const query of ["","---","… !!!"]){expect(()=>searchExamples(index,query)).toThrow(expect.objectContaining({code:"VGPU-EXAMPLES-USAGE",exitCode:2}));const result=await runExamples(["search",query],{fetchImpl:()=>{throw Error("network attempted")}});expect(result.code).toBe(2);expect(result).not.toHaveProperty("stdout");expect(JSON.parse(result.stderr!).error.code).toBe("VGPU-EXAMPLES-USAGE")}});

test("restores the old destination on a catchable termination signal",async()=>{const root=await temp("pull-term-"),out=join(root,"out");await mkdir(out);await writeFile(join(out,"old.txt"),"old");const moduleUrl=new URL("../../lib/examples/pull.js",import.meta.url).href,script=`import {pullExample} from ${JSON.stringify(moduleUrl)};const out=process.argv[1],manifest={files:[{path:'new.txt',size:3,sha256:'x'}]},client={getFile:async()=>Buffer.from('new')};await pullExample(client,manifest,out,{force:true,beforePublish:()=>{console.log('READY');return new Promise(()=>setInterval(()=>{},1000))}})`;const child=spawn(process.execPath,["--input-type=module","-e",script,out],{stdio:["ignore","pipe","inherit"]});await new Promise<void>((resolve,reject)=>{child.stdout!.on("data",chunk=>{if(String(chunk).includes("READY"))resolve()});child.once("error",reject)});child.kill("SIGTERM");await once(child,"close");expect(await readFile(join(out,"old.txt"),"utf8")).toBe("old")});

test("recovers after SIGKILL between old backup and new publication",async()=>{const root=await temp("pull-kill-"),out=join(root,"out");await mkdir(out);await writeFile(join(out,"old.txt"),"old");const moduleUrl=new URL("../../lib/examples/pull.js",import.meta.url).href,script=`import {pullExample} from ${JSON.stringify(moduleUrl)};const out=process.argv[1],manifest={files:[{path:'new.txt',size:3,sha256:'x'}]},client={getFile:async()=>Buffer.from('new')};await pullExample(client,manifest,out,{force:true,afterBackupRename:()=>{console.log('READY');return new Promise(()=>setInterval(()=>{},1000))}})`;const child=spawn(process.execPath,["--input-type=module","-e",script,out],{stdio:["ignore","pipe","inherit"]});await new Promise<void>((resolve,reject)=>{child.stdout!.on("data",chunk=>{if(String(chunk).includes("READY"))resolve()});child.once("error",reject)});child.kill("SIGKILL");await once(child,"close");const manifest:any={files:[{path:"new.txt",size:3,sha256:"x"}]},client:any={getFile:async()=>Buffer.from("new")};await pullExample(client,manifest,out,{force:true});expect(await readFile(join(out,"new.txt"),"utf8")).toBe("new");await expect(readFile(join(out,"old.txt"))).rejects.toMatchObject({code:"ENOENT"})});

test("cache descriptor traversal contains an ancestor swap race",async()=>{const root=await temp("cache-race2-"),outside=await temp("cache-race2-out-");const cache=new ExamplesCache(join(root,"cache")),target=cache.revisionDir(rev),held=join(root,"held");await mkdir(target,{recursive:true});for(let i=0;i<300;i++){const attack=(async()=>{try{await rename(target,held);await symlink(outside,target,"dir");await new Promise(r=>setImmediate(r));await rm(target);await rename(held,target)}catch{try{const s=await lstat(target);if(s.isSymbolicLink())await rm(target)}catch{}try{await rename(held,target)}catch{}}})();await Promise.allSettled([cache.write(cache.indexPath(rev),Buffer.from(`safe-${i}`)),attack])}await expect(readFile(join(outside,"index.json"))).rejects.toMatchObject({code:"ENOENT"})});

test("restores an authenticated backup before rejecting a hostile destination symlink",async()=>{const root=await temp("pull-backup-"),out=join(root,"out"),outside=await temp("pull-backup-out-");await mkdir(out);await writeFile(join(out,"old.txt"),"old");const moduleUrl=new URL("../../lib/examples/pull.js",import.meta.url).href,script=`import {pullExample} from ${JSON.stringify(moduleUrl)};const out=process.argv[1],manifest={files:[{path:'new.txt',size:3,sha256:'x'}]},client={getFile:async()=>Buffer.from('new')};await pullExample(client,manifest,out,{force:true,beforePublish:()=>{console.log('READY');return new Promise(()=>setInterval(()=>{},1000))}})`;const child=spawn(process.execPath,["--input-type=module","-e",script,out],{stdio:["ignore","pipe","inherit"]});await new Promise<void>((resolve,reject)=>{child.stdout!.on("data",chunk=>String(chunk).includes("READY")&&resolve());child.once("error",reject)});child.kill("SIGKILL");await once(child,"close");await symlink(outside,out,"dir");const manifest:any={files:[{path:"new.txt",size:3,sha256:"x"}]},client:any={getFile:async()=>Buffer.from("new")};await expect(pullExample(client,manifest,out)).rejects.toMatchObject({code:"VGPU-EXAMPLES-DESTINATION-EXISTS"});expect(await readFile(join(out,"old.txt"),"utf8")).toBe("old")});

test("recycled live PID with a different start time is stale",async()=>{const root=await temp("pull-pid-"),out=join(root,"out"),lock=join(root,".out.vgpu.lock"),token="a".repeat(32);await mkdir(lock);await writeFile(join(lock,"owner"),JSON.stringify({pid:process.pid,start:"0",token,temp:`.out.vgpu-tmp-${token}`,backup:`.out.vgpu-old-${token}`,stamp:`.out.vgpu-published-${token}`,phase:"locked"})+"\n");const manifest:any={files:[{path:"new.txt",size:3,sha256:"x"}]},client:any={getFile:async()=>Buffer.from("new")};await pullExample(client,manifest,out);expect(await readFile(join(out,"new.txt"),"utf8")).toBe("new")});

test("does not delete unauthenticated temp-prefix directories",async()=>{const root=await temp("pull-decoy-"),out=join(root,"out"),decoy=join(root,".out.vgpu-tmp-important");await mkdir(decoy);await writeFile(join(decoy,"valuable"),"keep");const manifest:any={files:[{path:"new.txt",size:3,sha256:"x"}]},client:any={getFile:async()=>Buffer.from("new")};await pullExample(client,manifest,out);expect(await readFile(join(decoy,"valuable"),"utf8")).toBe("keep")});

test("pull rejects a symlinked destination ancestor without writing outside",async()=>{const root=await temp("pull-parent-"),outside=await temp("pull-parent-out-"),link=join(root,"link"),out=join(link,"nested","out");await symlink(outside,link,"dir");const manifest:any={files:[{path:"new.txt",size:3,sha256:"x"}]},client:any={getFile:async()=>Buffer.from("new")};await expect(pullExample(client,manifest,out)).rejects.toMatchObject({code:"VGPU-EXAMPLES-FILESYSTEM"});await expect(readFile(join(outside,"nested","out","new.txt"))).rejects.toMatchObject({code:"ENOENT"})});

test("staging writes stay on the held directory when its pathname is swapped",async()=>{const root=await temp("pull-stage-write-"),out=join(root,"out"),outside=await temp("pull-stage-write-out-");let ready!:()=>void,resume!:()=>void;const paused=new Promise<void>(r=>ready=r),blocked=new Promise<void>(r=>resume=r),manifest:any={files:[{path:"nested/new.txt",size:3,sha256:"x"}]},client:any={getFile:async()=>{ready();await blocked;return Buffer.from("new")}};const pulling=pullExample(client,manifest,out);await paused;const entry=(await readdir(root)).find(value=>value.startsWith(".out.vgpu-tmp-"))!,staging=join(root,entry),held=join(root,"held");await rename(staging,held);await symlink(outside,staging,"dir");resume();await expect(pulling).rejects.toMatchObject({code:"VGPU-EXAMPLES-FILESYSTEM"});await expect(readFile(join(outside,"nested","new.txt"))).rejects.toMatchObject({code:"ENOENT"});expect(await readFile(join(held,"nested","new.txt"),"utf8")).toBe("new")});

test("publication rejects a swapped staging pathname instead of installing its symlink",async()=>{const root=await temp("pull-stage-publish-"),out=join(root,"out"),outside=await temp("pull-stage-publish-out-");await mkdir(out);await writeFile(join(out,"old.txt"),"old");let ready!:()=>void,resume!:()=>void;const paused=new Promise<void>(r=>ready=r),blocked=new Promise<void>(r=>resume=r),manifest:any={files:[{path:"new.txt",size:3,sha256:"x"}]},client:any={getFile:async()=>Buffer.from("new")};const pulling=pullExample(client,manifest,out,{force:true,beforePublish:async()=>{ready();await blocked}});await paused;const entry=(await readdir(root)).find(value=>value.startsWith(".out.vgpu-tmp-"))!,staging=join(root,entry),held=join(root,"held");await rename(staging,held);await symlink(outside,staging,"dir");resume();await expect(pulling).rejects.toMatchObject({code:"VGPU-EXAMPLES-FILESYSTEM"});expect((await lstat(out)).isDirectory()).toBe(true);expect((await lstat(out)).isSymbolicLink()).toBe(false);expect(await readFile(join(out,"old.txt"),"utf8")).toBe("old")});
