// Generated by apps/docs/scripts/sync-examples-api-contracts.mjs.
export const EXAMPLES_CONTRACT_ID = 'vgpu-examples/v1';
export const EXAMPLES_SCHEMA_SHA256 = '96acb9eef4ece73b508abd91685b27f81f523c008b36dd92f07f8013f61b4221';
export const EXAMPLES_SCHEMA_HASHES = {
  "discovery.schema.json": "0f5eb07ae720f6097a7b1e46b92751463d848cb19896f0fe8dc4f07c97ef0d44",
  "error.schema.json": "7966011fe073f416f95d3ea29b77121b68845583523e2306c659d373b33877ea",
  "index.schema.json": "ec41be4b211462d6ed62aa7ad0426d27daa81400535d9cda1d8a6a2ebae815c4",
  "manifest.schema.json": "f6b54de906fc8c096c603069ddf54e6d5eb067668609c106f5a080d0a20e59be"
};
