// This file is generated by scripts/ingest-examples.mjs. Do not edit by hand.

export interface ExampleThumbPresence {
  readonly card: string;
  readonly hero: string;
}

export const exampleThumbs: Record<string, ExampleThumbPresence> = {
  "gradient": {
    "card": "/examples/gradient.card.png",
    "hero": "/examples/gradient.hero.png"
  },
  "triangle-led-god-rays": {
    "card": "/examples/triangle-led-god-rays.card.png",
    "hero": "/examples/triangle-led-god-rays.hero.png"
  }
};
