// This file is generated by scripts/ingest-examples.mjs. Do not edit by hand.

export interface ExampleSourceFile {
  readonly name: string;
  readonly lang: string;
  readonly code: string;
}

export const exampleSources = {
  "gradient": [
    {
      "name": "example.ts",
      "lang": "typescript",
      "code": "import { init } from 'vgpu';\nimport fragment from './shader.wgsl';\n\nexport async function run(canvas: HTMLCanvasElement): Promise<() => void> {\n  const gpu = await init();\n  const surface = gpu.surface(canvas, { dpr: [1, 2] });\n  const effect = gpu.effect(fragment);\n  // TODO(vgpu): pre-warm the pipeline with effect.compile() once compile()/compileSync lands.\n  const handle = gpu.frame.loop((frame) => {\n    effect.set({ uniforms: { time: gpu.time, resolution: surface.size } });\n    frame.pass({ target: surface }, (p) => p.draw(effect));\n  });\n  return () => { handle.stop(); gpu.dispose(); };\n}\n"
    },
    {
      "name": "shader.wgsl",
      "lang": "wgsl",
      "code": "struct Uniforms {\n  time: f32,\n  resolution: vec2f,\n};\n@group(0) @binding(0) var<uniform> uniforms: Uniforms;\n\n@fragment\nfn fs_main(@builtin(position) position: vec4f) -> @location(0) vec4f {\n  let uv = position.xy / uniforms.resolution;\n  let vignette = smoothstep(1.2, 0.2, distance(uv, vec2f(0.5)));\n  return vec4f(uv.x, uv.y, 0.46 + 0.16 * vignette, 1.0);\n}\n"
    }
  ]
} as const satisfies Record<string, readonly ExampleSourceFile[]>;
