// This file is generated by scripts/ingest-examples.mjs. Do not edit by hand.

export interface ExampleThumbPresence {
  readonly card: string;
  readonly hero: string;
}

export const exampleThumbs: Record<string, ExampleThumbPresence> = {
  "anti-aliasing": {
    "card": "/examples/anti-aliasing.card.png",
    "hero": "/examples/anti-aliasing.hero.png"
  },
  "batch-rendering": {
    "card": "/examples/batch-rendering.card.png",
    "hero": "/examples/batch-rendering.hero.png"
  },
  "black-hole": {
    "card": "/examples/black-hole.card.png",
    "hero": "/examples/black-hole.hero.png"
  },
  "earth": {
    "card": "/examples/earth.card.png",
    "hero": "/examples/earth.hero.png"
  },
  "environment-map": {
    "card": "/examples/environment-map.card.png",
    "hero": "/examples/environment-map.hero.png"
  },
  "fft-ocean": {
    "card": "/examples/fft-ocean.card.png",
    "hero": "/examples/fft-ocean.hero.png"
  },
  "fluid": {
    "card": "/examples/fluid.card.png",
    "hero": "/examples/fluid.hero.png"
  },
  "gradient": {
    "card": "/examples/gradient.card.png",
    "hero": "/examples/gradient.hero.png"
  },
  "instanced-rendering": {
    "card": "/examples/instanced-rendering.card.png",
    "hero": "/examples/instanced-rendering.hero.png"
  },
  "nextjs-flare": {
    "card": "/examples/nextjs-flare.card.png",
    "hero": "/examples/nextjs-flare.hero.png"
  },
  "post-processing": {
    "card": "/examples/post-processing.card.png",
    "hero": "/examples/post-processing.hero.png"
  },
  "radiance-cascades": {
    "card": "/examples/radiance-cascades.card.png",
    "hero": "/examples/radiance-cascades.hero.png"
  },
  "raymarched-fractal": {
    "card": "/examples/raymarched-fractal.card.png",
    "hero": "/examples/raymarched-fractal.hero.png"
  },
  "transmission": {
    "card": "/examples/transmission.card.png",
    "hero": "/examples/transmission.hero.png"
  },
  "triangle-led-front": {
    "card": "/examples/triangle-led-front.card.png",
    "hero": "/examples/triangle-led-front.hero.png"
  }
};
