// This file is generated by scripts/ingest-examples.mjs. Do not edit by hand.

export interface ExampleThumbPresence {
  readonly card: string;
  readonly hero: string;
}

export const exampleThumbs: Record<string, ExampleThumbPresence> = {
  "anti-aliasing": {
    "card": "/examples/anti-aliasing.card.png",
    "hero": "/examples/anti-aliasing.hero.png"
  },
  "batch-rendering": {
    "card": "/examples/batch-rendering.card.png",
    "hero": "/examples/batch-rendering.hero.png"
  },
  "fluid": {
    "card": "/examples/fluid.card.png",
    "hero": "/examples/fluid.hero.png"
  },
  "gradient": {
    "card": "/examples/gradient.card.png",
    "hero": "/examples/gradient.hero.png"
  },
  "instanced-rendering": {
    "card": "/examples/instanced-rendering.card.png",
    "hero": "/examples/instanced-rendering.hero.png"
  },
  "post-processing": {
    "card": "/examples/post-processing.card.png",
    "hero": "/examples/post-processing.hero.png"
  },
  "triangle-led-front": {
    "card": "/examples/triangle-led-front.card.png",
    "hero": "/examples/triangle-led-front.hero.png"
  }
};
