// `LayoutProps<"/">` is generated by Next's typegen into .next/types/routes.d.ts, which
// this app's tsconfig already includes. Naming the props type that way (instead of
// importing `ReactNode` from "react") is deliberate: the workspace resolves two
// @types/react majors (18.x for this example and apps/docs, 19.x for apps/docs-next),
// and pnpm hoists only one of them to node_modules/.pnpm/node_modules/@types/react --
// nondeterministically, so identical `pnpm install --frozen-lockfile` runs differ. Next's
// own .d.ts files resolve React through that hoisted copy, so the generated
// `LayoutProps.children: React.ReactNode` was sometimes React 19's ReactNode (it includes
// `bigint`) while a locally imported ReactNode was always React 18's -- an incompatible
// pair that failed `next build`'s LayoutConfig<"/"> check roughly one run in six. Reusing
// the generated type keeps both sides on the same React namespace whichever copy wins.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
