export const meta = {
  slug: "mechanical-garden",
  title: "Mechanical Garden",
  guide: "/docs/guides/scene-composition",
  description:
    "Quadruped robot dogs trot across a gray training ground you can elevate and lower: math solves their legs with FABRIK, vgpu/scene instances every part.",
  tags: ["3d", "robotics", "inverse-kinematics", "scene-graph", "instancing", "terrain", "shadows"],
  capabilities: [
    "webgpu",
    "instanced-rendering",
    "pointer-orbit",
    "pointer-input",
    "keyboard-input",
    "fixed-timestep",
    "multi-pass",
    "render-targets",
    "controls",
    "responsive-canvas",
  ],
  files: [
    "index.tsx",
    "renderer.ts",
    "input.ts",
    "toolbar.ts",
    "camera.ts",
    "colony.ts",
    "robot.ts",
    "leg.ts",
    "terrain.ts",
    "rig.ts",
    "meshes.ts",
    "pipeline.ts",
    "common.wgsl",
    "parts.wgsl",
    "terrain.wgsl",
    "floor.wgsl",
    "shadow.wgsl",
    "debug.wgsl",
    "present.wgsl",
  ],
  thumb: { warmupFrames: 0, time: 0, dt: 1 / 60 },
} as const;
