import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "vitest";
import { createNodeAdapter } from "@vgpu/adapter-node";
import { App } from "@vgpu/core";
import { compile } from "@vgpu/wgsl";
import { resolveShader } from "@vgpu/wgsl/runtime";
import { transformWgsl } from "@vgpu/wgsl/loader-vite";
import wgslWebpackLoader from "@vgpu/wgsl/loader-webpack";
const validation = process.env.VGPU_DOCKER_TEST === "1";

describe("s3 §8 40-77", () => {
  test("40 raw import rejected", () => expect(() => compile("import { x } from './x.wgsl';")).toThrow(expect.objectContaining({ code: "VGPU-WGSL-RUNTIME-IMPORT" })));
  test("41 comment-only import accepted", () => expect(compile("// import { x } from './x.wgsl'\nfn main(){}").wgsl).toContain("fn main"));
  test("42 namespace assignment rejected", async () => await nsValue("let m = math;"));
  test("43 namespace argument rejected", async () => await nsValue("foo(math);"));
  test("44 namespace computed access rejected", async () => await nsValue("math[0];"));
  test("45 enable argument is not substituted", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { f16 } from './p.wgsl'; enable f16; fn main(){f16();}", "/p.wgsl": "export fn f16(){}" }, validate: false })).wgsl).toContain("enable f16;"));
  test("46 requires argument is not substituted", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { subgroup_uniform_control_flow } from './p.wgsl'; requires subgroup_uniform_control_flow; fn main(){subgroup_uniform_control_flow();}", "/p.wgsl": "export fn subgroup_uniform_control_flow(){}" }, validate: false })).wgsl).toContain("requires subgroup_uniform_control_flow;"));
  test("47 struct field declaration not substituted", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { foo } from './p.wgsl'; struct S { foo: f32 } fn main(){foo();}", "/p.wgsl": "export fn foo() -> f32 {return 1.0;}" }, validate: false })).wgsl).toContain("foo: f32"));
  test("48 function parameter declaration not substituted", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { foo } from './p.wgsl'; fn f(foo: f32){ let x = foo; }", "/p.wgsl": "export fn foo() -> f32 {return 1.0;}" }, validate: false })).wgsl).toContain("let x = foo"));
  test("49 for-loop local shadows", async () => expect((await shadows("for (var i = 0u; i < 2u; i = i + 1u) {}", "i")).wgsl).toContain("i = i + 1u"));
  test("50 loop local shadows", async () => expect((await shadows("loop { var x = 0u; let y = x; break; }", "x")).wgsl).toContain("let y = x"));
  test("51 switch case local shadows", async () => expect((await shadows("switch (0u) { case 0u: { let bar = 1u; let y = bar; } default: {} }", "bar")).wgsl).toContain("let y = bar"));
  test("52 function parameter shadows", async () => expect((await shadows("fn f(foo: u32){ let y = foo; }", "foo")).wgsl).toContain("let y = foo"));
  test("53 duplicate reachable overrides error", async () => await expect(resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { a } from './a.wgsl'; import { b } from './b.wgsl';", "/a.wgsl": "override SAMPLES=1; export fn a(){}", "/b.wgsl": "override SAMPLES=2; export fn b(){}" }, validate: false })).rejects.toMatchObject({ code: "VGPU-WGSL-OVERRIDE-DUP" }));
  test("54 unreachable duplicate overrides ignored", async () => await expect(resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "override SAMPLES=1;", "/u.wgsl": "override SAMPLES=2;" }, validate: false })).resolves.toHaveProperty("wgsl"));
  test("55 duplicate entry points error", async () => await expect(resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { a } from './a.wgsl'; @compute @workgroup_size(1) fn main(){}", "/a.wgsl": "@compute @workgroup_size(1) export fn main(){} export fn a(){}" }, validate: false })).rejects.toMatchObject({ code: "VGPU-WGSL-ENTRYPOINT-DUP" }));
  test("57 entry point names are not mangled", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "@compute @workgroup_size(1) fn main(){}" }, validate: false })).wgsl).toContain("fn main("));
  test("58 original entry-point appears verbatim", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "@compute @workgroup_size(1) fn main(){}" }, validate: false })).wgsl.includes("fn main(")).toBe(true));
  test("59 override name appears verbatim", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "override SAMPLES: u32 = 4u;" }, validate: false })).wgsl).toContain("override SAMPLES"));
  test.skipIf(process.env.VGPU_DOCKER_TEST !== "1")("60 pipeline constants work on Dawn", async () => { const { device } = await App.create({ adapter: createNodeAdapter() }); const shader = await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { out } from './buf.wgsl'; override SAMPLES: u32 = 1u; @compute @workgroup_size(1) fn main(){ out.value = SAMPLES; }", "/buf.wgsl": "struct Out { value: u32 } @group(0) @binding(0) export var<storage, read_write> out: Out;" }, validate: false }); const gpu = device.gpu; const b = gpu.createBuffer({ size: 4, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST }); gpu.queue.writeBuffer(b, 0, new Uint32Array([0])); const r = gpu.createBuffer({ size: 4, usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST }); const constants: Record<string, number> = {}; constants["SAMPLES"] = 8; const p = gpu.createComputePipeline({ layout: "auto", compute: { module: gpu.createShaderModule({ code: shader.wgsl }), entryPoint: "main", constants } }); const bg = gpu.createBindGroup({ layout: p.getBindGroupLayout(0), entries: [{ binding: 0, resource: { buffer: b } }] }); const e = gpu.createCommandEncoder(); const pass = e.beginComputePass(); pass.setPipeline(p); pass.setBindGroup(0, bg); pass.dispatchWorkgroups(1); pass.end(); e.copyBufferToBuffer(b, 0, r, 0, 4); gpu.queue.submit([e.finish()]); await gpu.queue.onSubmittedWorkDone(); await r.mapAsync(GPUMapMode.READ); expect(new Uint32Array(r.getMappedRange()).slice()[0]).toBe(8); r.unmap(); device.destroy(); });
  test.skipIf(process.env.VGPU_DOCKER_TEST !== "1")("61 entry point main works and mangled fails", async () => { const { device } = await App.create({ adapter: createNodeAdapter() }); const shader = await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "@compute @workgroup_size(1) fn main(){}" }, validate: false }); expect(shader.reflection.entryPoints[0]).toMatchObject({ name: "main", mangledName: "main" }); expect(() => device.gpu.createComputePipeline({ layout: "auto", compute: { module: device.gpu.createShaderModule({ code: shader.wgsl }), entryPoint: "main" } })).not.toThrow(); device.gpu.pushErrorScope("validation"); device.gpu.createComputePipeline({ layout: "auto", compute: { module: device.gpu.createShaderModule({ code: shader.wgsl }), entryPoint: "_vgsl_deadbeef__main" } }); expect(await device.gpu.popErrorScope()).toBeTruthy(); device.destroy(); });
  test("62 missing package errors", async () => await expect(resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { x } from 'missing-pkg';" }, validate: false })).rejects.toMatchObject({ code: "VGPU-WGSL-PKG-NOTFOUND" }));
  test("63 packageMap takes precedence", async () => expect((await resolveShader({ entry: "/m.wgsl", packageMap: { "missing-pkg": "/pkg/index.wgsl" }, modules: { "/m.wgsl": "import { x } from 'missing-pkg'; fn main(){x();}", "/pkg/index.wgsl": "export fn x(){}" }, validate: false })).wgsl).toContain("/pkg/index.wgsl"));
  test("64 package exports pattern resolves", async () => { const dir = await pkgFixture({ exports: { "./shaders/*": "./dist/*.wgsl" }, files: { "dist/foo.wgsl": "export fn x(){}" } }); await writeFile(join(dir, "app", "main.wgsl"), "import { x } from 'pkg/shaders/foo'; fn main(){x();}"); expect((await resolveShader({ entry: join(dir, "app", "main.wgsl"), validate: false })).wgsl).toContain("dist/foo.wgsl"); });
  test("65 walking stops at workspace root", async () => { const dir = await mkdtemp(join(tmpdir(), "vgsl-")); await mkdir(join(dir, "root", "app"), { recursive: true }); await mkdir(join(dir, "node_modules", "pkg"), { recursive: true }); await writeFile(join(dir, "root", "pnpm-workspace.yaml"), "packages: []"); await writeFile(join(dir, "root", "app", "main.wgsl"), "import { x } from 'pkg';"); await writeFile(join(dir, "node_modules", "pkg", "package.json"), JSON.stringify({ exports: { ".": "./index.wgsl" } })); await writeFile(join(dir, "node_modules", "pkg", "index.wgsl"), "export fn x(){}"); await expect(resolveShader({ entry: join(dir, "root", "app", "main.wgsl"), validate: false })).rejects.toMatchObject({ code: "VGPU-WGSL-PKG-NOTFOUND" }); });
  test("66 conditional exports select default", async () => { const dir = await pkgFixture({ exports: { ".": { import: "./bad.wgsl", default: "./good.wgsl" } }, files: { "good.wgsl": "export fn x(){}" } }); await writeFile(join(dir, "app", "main.wgsl"), "import { x } from 'pkg'; fn main(){x();}"); const result = await resolveShader({ entry: join(dir, "app", "main.wgsl"), validate: false }); expect(result.wgsl).toContain("good.wgsl"); expect(result.diagnostics).toEqual([expect.objectContaining({ code: "VGPU-WGSL-PKG-CONDITIONAL", severity: "warning" })]); });
  test("67 cacheKey regex and repeat equality", async () => { const r = await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "@compute @workgroup_size(1) fn main(){}" }, validate: false }); expect(r.cacheKey.main).toMatch(/^vgsl-1:[0-9a-f]{32}$/); expect(r.cacheKey).toEqual((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "@compute @workgroup_size(1) fn main(){}" }, validate: false })).cacheKey); });
  test("68 comments ignored by cacheKey", async () => expect((await ck("// a\nfn main(){}"))).toEqual(await ck("// b\nfn main(){}")));
  test("69 whitespace ignored by cacheKey", async () => expect(await ck("fn main(){ return; }")).toEqual(await ck("fn   main() {\n return;\n}")));
  test("70 semantic body change differs", async () => expect(await ck("fn main(){ let x = 1; }")).not.toEqual(await ck("fn main(){ let x = 2; }")));
  test("71 mangle spelling ignored", async () => { const source = "import { x } from './a.wgsl'; fn main(){x();}"; const a = await resolveShader({ entry: "/tmp/a/proj/m.wgsl", rootDir: "/tmp/a/proj", modules: { "/tmp/a/proj/m.wgsl": source, "/tmp/a/proj/a.wgsl": "export fn x(){}" }, validate: false }); const b = await resolveShader({ entry: "/tmp/b/proj/m.wgsl", rootDir: "/tmp/b/proj", modules: { "/tmp/b/proj/m.wgsl": source, "/tmp/b/proj/a.wgsl": "export fn x(){}" }, validate: false }); expect(a.wgsl).not.toBe(b.wgsl); expect(a.cacheKey).toEqual(b.cacheKey); });
  test("72 cross-machine deterministic snapshot", async () => expect((await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "@compute @workgroup_size(1) fn main(){}" }, validate: false })).cacheKey.main).toBe("vgsl-1:d4b13650ab62922eb74c26a5a098c79d"));
  test.skipIf(!validation)("73 approximate diagnostic tagged", async () => await expect(resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { f } from './f.wgsl'; fn main(){ let x: u32 = f(); }", "/f.wgsl": "export fn f() -> f32 { return 1.0; }" } })).rejects.toMatchObject({ code: "VGPU-WGSL-NAGA-UNKNOWN", columnPrecise: false, relatedDiagnostics: [expect.objectContaining({ code: "VGPU-WGSL-COL-APPROX" })] }));
  test.skipIf(!validation)("74 precise diagnostic before substitution", async () => { try { await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "@compute @workgroup_size(1) fn main(){ let x: u32 = 1.0; }" } }); throw new Error("expected validation failure"); } catch (error) { expect(error).toMatchObject({ code: "VGPU-WGSL-NAGA-UNKNOWN", range: { file: "m.wgsl" }, columnPrecise: true }); expect(JSON.stringify(error)).not.toContain("VGPU-WGSL-COL-APPROX"); } });
  test("75 loader comment-only import passes through", async () => expect((await transformWgsl("// import { x } from 'y'", "/x.wgsl")).code).toContain("// import"));
  test("76 loaders resolve top-level import", async () => { const dir = await mkdtemp(join(tmpdir(), "vgsl-")); await writeFile(join(dir, "main.wgsl"), "import { x } from './x.wgsl'; fn main(){x();}"); await writeFile(join(dir, "x.wgsl"), "export fn x(){}"); expect((await transformWgsl(await (await import("node:fs/promises")).readFile(join(dir, "main.wgsl"), "utf8"), join(dir, "main.wgsl"))).code).toContain("_vgsl_"); const code = await webpack(join(dir, "main.wgsl"), await (await import("node:fs/promises")).readFile(join(dir, "main.wgsl"), "utf8")); expect(code).toContain("_vgsl_"); });
  test("77 attribute align preserved while value align substituted", async () => { const out = (await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": "import { align } from './a.wgsl'; struct S { @align(16) x: u32 } fn main(){align();}", "/a.wgsl": "export fn align(){}" }, validate: false })).wgsl; expect(out).toContain("@align(16)"); expect(out).toContain("_vgsl_"); });
});

async function nsValue(expr: string): Promise<void> { await expect(resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": `import * as math from './p.wgsl'; fn foo(){} fn main(){ ${expr} }`, "/p.wgsl": "export fn x(){}" }, validate: false })).rejects.toMatchObject({ code: "VGPU-WGSL-NS-NOTVALUE" }); }
async function shadows(body: string, name: string) { return resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": `import { ${name} } from './p.wgsl'; ${body.startsWith("fn") ? body : `fn f(){ ${body} }`}`, "/p.wgsl": `export fn ${name}(){}` }, validate: false }); }
async function ck(source: string) { return (await resolveShader({ entry: "/m.wgsl", modules: { "/m.wgsl": source }, validate: false })).cacheKey; }
async function pkgFixture(opts: { exports: unknown; files: Record<string, string> }) { const dir = await mkdtemp(join(tmpdir(), "vgsl-")); await mkdir(join(dir, "app"), { recursive: true }); await mkdir(join(dir, "node_modules", "pkg"), { recursive: true }); await writeFile(join(dir, "node_modules", "pkg", "package.json"), JSON.stringify({ exports: opts.exports })); for (const [file, text] of Object.entries(opts.files)) { await mkdir(join(dir, "node_modules", "pkg", file.split("/").slice(0, -1).join("/")), { recursive: true }); await writeFile(join(dir, "node_modules", "pkg", file), text); } return dir; }
async function webpack(resourcePath: string, source: string) { return new Promise<string>((resolve, reject) => wgslWebpackLoader.call({ resourcePath, async: () => (error, result) => error ? reject(error) : resolve(result ?? "") }, source)); }
