export const meta = {
  slug: "optimized-black-hole",
  title: "Optimized Black Hole",
  description:
    "A multi-pass black hole that bakes relativistic ray traversal once into a G-buffer, then reuses it for animated disk shading, stars, antialiasing and HDR bloom.",
  tags: ["black-hole", "raymarching", "performance", "hdr", "bloom", "shader"],
  capabilities: [
    "webgpu",
    "pointer-orbit",
    "multi-pass",
    "render-targets",
    "offscreen-rendering",
    "continuous-rendering",
    "responsive-canvas",
    "textures",
    "hdr",
  ],
  thumb: { warmupFrames: 1, time: 2.5, dt: 1 / 60 },
  files: [
    "index.tsx",
    "renderer.ts",
    "settings.ts",
    "pipeline.ts",
    "noise-volume.mjs",
    "bake.wgsl",
    "refine.wgsl",
    "gbuffer.wgsl",
    "geodesic.wgsl",
    "shade.wgsl",
    "disk.wgsl",
    "stars.wgsl",
    "bloom.wgsl",
    "composite.wgsl",
  ],
} as const;
