import type { ExampleMetaDefinition } from "../../lib/example-meta";

export const meta = {
  slug: "glass-fractal",
  title: "Glass Fractal",
  description:
    "A beveled glass tetrahedron contains a morphing fractal mesh and liquid orb, combining screen-space transmission, studio reflections, soft material lighting and interactive controls.",
  tags: ["fractal", "frosted-glass", "lighting", "hdr", "shader"],
  capabilities: [
    "webgpu",
    "controls",
    "pointer-input",
    "multi-pass",
    "render-targets",
    "continuous-rendering",
    "responsive-canvas",
    "textures",
    "hdr",
  ],
  thumb: {
    warmupFrames: 1,
    time: 0,
    dt: 0,
  },
  files: [
    "index.tsx",
    "renderer.ts",
    "scene.ts",
    "settings.ts",
    "hero-glass-assets.ts",
    "hero-glass-assets-core.ts",
    "hero-debug-axes.wgsl",
    "hero-fractal-background-draw.wgsl",
    "hero-fractal-ceramic.wgsl",
    "hero-fractal-face-instance.wgsl",
    "hero-fractal-floor-ao.wgsl",
    "hero-fractal-light.wgsl",
    "hero-fractal-mesh.wgsl",
    "hero-fractal-present.wgsl",
    "hero-fractal-sdf.wgsl",
    "hero-fractal-wireframe.wgsl",
    "hero-glass-environment-debug.wgsl",
    "hero-glass-environment.wgsl",
    "hero-glass-transmission.wgsl",
    "hero-glass-wireframe.wgsl",
    "hero-glass.wgsl",
  ],
} as const satisfies ExampleMetaDefinition;
