/**
 * Browser lifecycle: ONNX Runtime Web owns the WebGPU device, vgpu adopts it,
 * and every frame's GPU-resident output is presented through a non-owning wrap.
 *
 * Per frame, exactly once and never overlapping:
 *   create 4-byte time tensor -> session.run -> retain output -> wrapBuffer ->
 *   draw -> await queue.flush() -> wrapper.dispose() -> output.dispose() ->
 *   time.dispose()
 *
 * The 1 MiB image never returns to the CPU and is never copied.
 */
import type { Buffer, Gpu, Surface } from 'vgpu';
import type { BrowserRendererOptions, ExampleRenderer, RenderSize } from '../../lib/example-renderer';
import {
  assertGpuTensor,
  createSharedDeviceSession,
  OrtEnvironmentError,
  OrtInitCancelled,
  withWrappedTensor,
  type OrtTensor,
  type SharedDeviceSession,
} from '../../lib/ort-webgpu';
import { asWriteData, coordinateGrid, GRID, PIXELS, TIME_SCALE } from './evaluate';
import { createFpsMeter, createFramePump, type FramePump } from './frame-pump';
import { createPresentPipeline, type PresentPipeline } from './renderer';

/** Same-origin model asset; generated by `generate-model.mjs`. */
export const MODEL_URL = '/examples/neural-shader-cppn/model.onnx';

/** How the persistent coordinate tensor is fed to ORT. */
export type CoordinateInputMode = 'gpu-buffer' | 'cpu-tensor';

export interface CppnStatus {
  readonly phase: 'initializing' | 'running' | 'unsupported' | 'error';
  readonly detail?: string;
  readonly fps?: number;
  readonly inputMode?: CoordinateInputMode;
}

export interface CppnRendererOptions extends BrowserRendererOptions {
  readonly onStatus?: (status: CppnStatus) => void;
}

export function createRenderer(options: CppnRendererOptions): ExampleRenderer {
  let disposed = false;
  let reportedError = false;
  let shared: SharedDeviceSession | undefined;
  let gpu: Gpu | undefined;
  let surface: Surface | undefined;
  let pipeline: PresentPipeline | undefined;
  let coordsBuffer: Buffer | undefined;
  let coordsTensor: OrtTensor | undefined;
  let coordsData: Float32Array | undefined;
  let inputMode: CoordinateInputMode = 'gpu-buffer';
  let pump: FramePump | undefined;
  let shutdown: Promise<void> | undefined;
  let observer: ResizeObserver | undefined;
  let resizeFrame = 0;
  let pendingSize: RenderSize | undefined;
  let lastDpr = typeof window === 'undefined' ? 1 : window.devicePixelRatio;
  let startMs: number | undefined;
  let loggedEvidence = false;
  const fpsMeter = createFpsMeter();

  const status = (next: CppnStatus) => {
    if (disposed && next.phase === 'running') return;
    try {
      options.onStatus?.({ inputMode, ...next });
    } catch {
      // Status reporting must never break rendering.
    }
  };

  const applyResize = () => {
    resizeFrame = 0;
    const size = pendingSize;
    pendingSize = undefined;
    if (disposed || !size || !surface) return;
    try {
      // Only the surface resizes; inference stays at the model's fixed grid.
      surface.resize([
        Math.max(1, Math.round(size.width * size.dpr)),
        Math.max(1, Math.round(size.height * size.dpr)),
      ]);
    } catch (error) {
      handleFailure(error);
    }
  };
  const resize = (size: RenderSize) => {
    if (disposed || size.width <= 0 || size.height <= 0) return;
    pendingSize = size;
    if (!resizeFrame) resizeFrame = requestAnimationFrame(applyResize);
  };
  const measure = () => {
    const rect = options.canvas.getBoundingClientRect();
    resize({
      width: rect.width,
      height: rect.height,
      dpr: Math.min(2, Math.max(1, window.devicePixelRatio || 1)),
    });
  };
  const onWindowResize = () => {
    if (window.devicePixelRatio === lastDpr) return;
    lastDpr = window.devicePixelRatio;
    measure();
  };

  /** Runs one complete inference + presentation frame. */
  const runFrame = async (timestampMs: number): Promise<void> => {
    if (disposed || !shared || !gpu || !surface || !pipeline || !coordsTensor) return;
    startMs ??= timestampMs;
    const seconds = (timestampMs - startMs) / 1000;
    const { ort, session } = shared;

    const time = new ort.Tensor('float32', new Float32Array([seconds * TIME_SCALE]), [1, 1]);
    let output: OrtTensor | undefined;
    try {
      const outputs = await session.run({ coords: coordsTensor, time });
      if (disposed) return;
      output = outputs[session.outputNames[0]!];
      const raw = assertGpuTensor(output, {
        dataType: 'float32',
        dims: [1, GRID, GRID, 4],
        label: 'neural-shader-cppn rgba',
      });
      // retain -> wrap -> submit -> flush -> wrapper dispose (inside), then the
      // tensor is released in this function's finally.
      await withWrappedTensor(gpu, raw, (wrapped) => {
        if (!loggedEvidence) {
          loggedEvidence = true;
          // One-time diagnostic line: makes the interop contract observable in a
          // real browser without reading any tensor data back to the CPU.
          console.info('[neural-shader-cppn] interop', {
            deviceIdentity: gpu!.gpu === shared!.device,
            outputLocation: 'gpu-buffer',
            outputBytes: raw.size,
            wrapperRawIdentity: wrapped.gpu === raw,
            dims: [1, GRID, GRID, 4],
            coordinateInput: inputMode,
          });
        }
        pipeline!.draw(gpu!, surface!, wrapped, seconds);
      });
      const fps = fpsMeter.sample(timestampMs);
      if (fps !== undefined) status({ phase: 'running', fps });
    } finally {
      output?.dispose();
      time.dispose();
    }
  };

  const dispose = () => {
    if (disposed) return;
    disposed = true;
    if (resizeFrame) cancelAnimationFrame(resizeFrame);
    resizeFrame = 0;
    pendingSize = undefined;
    observer?.disconnect();
    observer = undefined;
    if (typeof window !== 'undefined') window.removeEventListener('resize', onWindowResize);
    const active = pump?.stop();
    pump = undefined;
    // One idempotent async shutdown: drain the frame that borrowed ORT's buffer
    // before releasing anything it touches.
    shutdown ??= (async () => {
      await Promise.allSettled([active ?? Promise.resolve()]);
      try {
        coordsTensor?.dispose();
      } catch {
        // The tensor never owned the buffer; disposal problems are not fatal.
      }
      coordsTensor = undefined;
      coordsBuffer?.dispose();
      coordsBuffer = undefined;
      pipeline?.dispose();
      pipeline = undefined;
      surface?.dispose();
      surface = undefined;
      // Disposes the vgpu facade first, then releases the ORT session.
      await shared?.release();
      shared = undefined;
      gpu = undefined;
    })().catch(() => undefined);
  };

  const initialize = async () => {
    status({ phase: 'initializing' });
    shared = await createSharedDeviceSession({
      modelUrl: MODEL_URL,
      label: 'neural-shader-cppn',
      isCancelled: () => disposed,
      onStage: (stage) => status({ phase: 'initializing', detail: stage }),
    });
    if (disposed) return;
    gpu = shared.gpu;

    surface = gpu.surface(options.canvas, { dpr: [1, 2] });
    pipeline = createPresentPipeline(gpu);

    // The coordinate grid is uploaded exactly once and lives on the GPU for the
    // whole session; only four bytes of time cross the boundary per frame.
    coordsData = coordinateGrid();
    coordsBuffer = gpu.device.createBuffer({
      size: coordsData.byteLength,
      usage: ['storage', 'copy_dst', 'copy_src'],
      label: 'neural-shader-cppn-coords',
    });
    coordsBuffer.write(asWriteData(coordsData));
    await gpu.device.queue.flush();
    if (disposed) return;

    coordsTensor = createCoordinateTensor(shared, coordsBuffer);

    observer = typeof ResizeObserver === 'undefined' ? undefined : new ResizeObserver(measure);
    observer?.observe(options.canvas);
    window.addEventListener('resize', onWindowResize);
    measure();

    // A first run proves the graph and input mode before the pump starts, and
    // lets the GPU-input fallback happen once instead of every frame.
    await warmup();
    if (disposed) return;

    status({ phase: 'running' });
    pump = createFramePump({
      requestFrame: (callback) => requestAnimationFrame(callback),
      cancelFrame: (handle) => cancelAnimationFrame(handle),
      run: runFrame,
      onError: handleFailure,
    });
    pump.start();
  };

  /**
   * Creates the persistent coordinate tensor. vgpu owns the buffer, so no
   * disposer is registered with ORT.
   */
  function createCoordinateTensor(session: SharedDeviceSession, buffer: Buffer): OrtTensor {
    if (inputMode === 'cpu-tensor') {
      return new session.ort.Tensor('float32', coordsData!, [PIXELS, 2]);
    }
    return session.ort.Tensor.fromGpuBuffer(buffer.gpu, {
      dataType: 'float32',
      dims: [PIXELS, 2],
    });
  }

  /**
   * Runs one throwaway frame. If ORT rejects the GPU-resident coordinate input,
   * fall back once to a CPU tensor that is still uploaded from the same cached
   * array instead of being rebuilt per frame.
   */
  async function warmup(): Promise<void> {
    try {
      await runFrame(performance.now());
    } catch (error) {
      if (disposed || inputMode === 'cpu-tensor') throw error;
      inputMode = 'cpu-tensor';
      status({
        phase: 'initializing',
        detail: 'GPU-resident coordinate input rejected; using a cached CPU input tensor.',
      });
      try {
        coordsTensor?.dispose();
      } catch {
        // Falling back must not be blocked by the rejected tensor.
      }
      coordsTensor = createCoordinateTensor(shared!, coordsBuffer!);
      await runFrame(performance.now());
    }
  }

  function handleFailure(error: unknown): void {
    if (disposed || error instanceof OrtInitCancelled) return;
    if (!reportedError) {
      reportedError = true;
      const unsupported = error instanceof OrtEnvironmentError;
      status({
        phase: unsupported ? 'unsupported' : 'error',
        detail: error instanceof Error ? error.message : String(error),
      });
      try {
        options.onError?.(error);
      } catch {
        // Error reporting must not block teardown.
      }
    }
    dispose();
  }

  const ready = initialize().catch((error: unknown) => {
    if (disposed || error instanceof OrtInitCancelled) return;
    handleFailure(error);
    throw error;
  });

  return { ready, invalidate() {}, resize, dispose };
}
