export const meta = {
  slug: "modular-city",
  title: "Modular City",
  guide: "/docs/guides/scene-composition",
  description:
    "A miniature city whose neighborhoods are vgpu/scene groups of instance records; tap a building to pick it with a GPU ID pass, then edit it.",
  tags: ["3d", "scene-graph", "instancing", "picking", "lighting"],
  capabilities: [
    "webgpu",
    "instanced-rendering",
    "pointer-orbit",
    "pointer-input",
    "gpu-readback",
    "multi-pass",
    "render-targets",
    "controls",
    "responsive-canvas",
  ],
  files: [
    "index.tsx",
    "renderer.ts",
    "orbit-input.ts",
    "city.ts",
    "layout.ts",
    "pipeline.ts",
    "picking.ts",
    "common.wgsl",
    "city.wgsl",
    "ground.wgsl",
    "pick.wgsl",
    "shadow.wgsl",
    "present.wgsl",
  ],
} as const;
