export const meta = {
  slug: "air-painting",
  title: "Air Painting",
  description:
    "Wipe fog off the glass with your hands. ONNX Runtime Web tracks both palms on WebGPU to clear a frosted camera feed.",
  tags: [
    "machine-learning",
    "onnx",
    "hand-tracking",
    "frosted-glass",
    "shader",
  ],
  capabilities: [
    "webgpu",
    "machine-learning",
    "external-device",
    "zero-copy",
    "gpu-buffer-interop",
    "storage-buffers",
    "compute-shader",
    "camera-input",
    "textures",
    "continuous-rendering",
    "responsive-canvas",
  ],
  thumb: {
    warmupFrames: 1,
    dt: 1 / 30,
    note:
      "Procedural frame frosted and wiped by the golden two-handed [1,63] landmark " +
      "trajectory through the production shaders; no ORT in the Node path.",
  },
  files: [
    "index.tsx",
    "renderer.ts",
    "ort-runtime.ts",
    "ort-webgpu.ts",
    "visual-pipeline.ts",
    "inference-scheduler.ts",
    "camera-source.ts",
    "hand-model-contract.ts",
    "hand-pipeline.ts",
    "hand-tracker.ts",
    "fixtures.ts",
    "hand-crop.wgsl",
    "hand.wgsl",
    "paint.wgsl",
    "composite.wgsl",
    "frost.wgsl",
  ],
} as const;
