export const meta = {
  slug: 'spiral-galaxy',
  title: 'Spiral Galaxy',
  description:
    'A launch-page star-field hero built end to end on vgpu: a compute pass flows 4,600 stars along procedural spiral strokes, converges them from a scattered sky and runs a pointer-repel simulation; additive quads draw them into an HDR scene; a bloom, lens-flare and dirty-glass chain finishes with ACES tone mapping. Drag to rotate, hover to scatter.',
  tags: [
    'particles',
    'compute',
    'simulation',
    'instancing',
    'hdr',
    'bloom',
    'flare',
    'post-processing',
    'animation',
  ],
  capabilities: [
    'webgpu',
    'compute-shader',
    'storage-buffers',
    'instanced-rendering',
    'render-targets',
    'multi-pass',
    'hdr',
    'textures',
    'pointer-input',
    'controls',
    'checkbox-controls',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: {
    warmupFrames: 60,
    dt: 1 / 60,
    time: 7,
    requiredLimits: { maxStorageBuffersInVertexStage: 1 },
  },
  files: [
    'index.tsx',
    'renderer.ts',
    'pipeline.ts',
    'field.ts',
    'animation.ts',
    'input.ts',
    'simulate.wgsl',
    'stars.wgsl',
    'bright.wgsl',
    'blur.wgsl',
    'dirt.wgsl',
    'composite.wgsl',
  ],
} as const;
