export const meta = {
  slug: 'spring-choreography',
  title: 'Spring Choreography',
  description:
    'A quarter of a million GPU particles morph between shapes, each on a real Motion spring and stagger, sequenced by a scrubbable Motion timeline.',
  tags: ['motion', 'particles', 'spring', 'animation', 'compute', 'instancing', 'bloom', 'hdr'],
  capabilities: [
    'webgpu',
    'external-ticker',
    'compute-shader',
    'storage-buffers',
    'instanced-rendering',
    'render-targets',
    'multi-pass',
    'hdr',
    'pointer-input',
    'controls',
    'select-control',
    'checkbox-controls',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: {
    warmupFrames: 1,
    dt: 1 / 60,
    time: 6.4,
    requiredLimits: { maxStorageBuffersInVertexStage: 1 },
  },
  files: [
    'index.tsx',
    'renderer.ts',
    'choreography.ts',
    'pipeline.ts',
    'swarm.wgsl',
    'sprites.wgsl',
    'fade.wgsl',
    'bright.wgsl',
    'blur.wgsl',
    'composite.wgsl',
  ],
} as const;
