export { EditableMesh } from "./editable-mesh.ts";
export { MeshEditError } from "./errors.ts";
export { MeshEditWarning } from "./warnings.ts";
export { toEditable, toEditableWithDiagnostics } from "./to-editable.ts";
export { extrude } from "./operators/extrude.ts";
export { bevel } from "./operators/bevel.ts";
export { inset } from "./operators/inset.ts";
export { subdivideEdges } from "./operators/subdivide-edges.ts";
export { subdivideFaces } from "./operators/subdivide-faces.ts";
export { loopCut } from "./operators/loop-cut.ts";
export { bridge } from "./operators/bridge.ts";
export { fillHole } from "./operators/fill-hole.ts";
export { gridFill } from "./operators/grid-fill.ts";
export { dissolveVertices } from "./operators/dissolve-vertices.ts";
export { dissolveEdges } from "./operators/dissolve-edges.ts";
export { dissolveFaces } from "./operators/dissolve-faces.ts";
export { mergeByDistance } from "./operators/merge-by-distance.ts";
export { healManifold } from "./operators/heal-manifold.ts";
export { recomputeNormals } from "./operators/recompute-normals.ts";
export type { MeshEditErrorCode } from "./errors.ts";
export type { MeshEditWarningCode } from "./warnings.ts";
export type { ExtrudeOptions, ExtrudeResult } from "./operators/extrude.ts";
export type { BevelOptions, BevelResult } from "./operators/bevel.ts";
export type { InsetOptions, InsetResult } from "./operators/inset.ts";
export type { SubdivideEdgesOptions, SubdivideEdgesResult } from "./operators/subdivide-edges.ts";
export type { SubdivideFacesOptions, SubdivideFacesResult } from "./operators/subdivide-faces.ts";
export type { LoopCutOptions, LoopCutResult } from "./operators/loop-cut.ts";
export type { BridgeOptions, BridgeResult } from "./operators/bridge.ts";
export type { FillHoleOptions, FillHoleResult } from "./operators/fill-hole.ts";
export type { GridFillOptions, GridFillResult } from "./operators/grid-fill.ts";
export type { DissolveVerticesOptions, DissolveVerticesResult } from "./operators/dissolve-vertices.ts";
export type { DissolveEdgesOptions, DissolveEdgesResult } from "./operators/dissolve-edges.ts";
export type { DissolveFacesResult } from "./operators/dissolve-faces.ts";
export type { MergeByDistanceOptions, MergeByDistanceResult } from "./operators/merge-by-distance.ts";
export type { HealManifoldReport, HealManifoldResult } from "./operators/heal-manifold.ts";
export type { RecomputeNormalsOptions, RecomputeNormalsResult } from "./operators/recompute-normals.ts";
export type { EditableMesh as EditableMeshValue, EdgeView, ElementDomain, ElementSelection, ElementSet, FaceView, ScoredSelection, VertexView } from "./types.ts";
