export { EditableMesh } from "./editable-mesh.ts";
export { MeshEditError } from "./errors.ts";
export { MeshEditWarning } from "./warnings.ts";
export { toEditable, toEditableWithDiagnostics } from "./to-editable.ts";
export { extrude } from "./operators/extrude.ts";
export { bevel } from "./operators/bevel.ts";
export { inset } from "./operators/inset.ts";
export type { MeshEditErrorCode } from "./errors.ts";
export type { MeshEditWarningCode } from "./warnings.ts";
export type { ExtrudeOptions, ExtrudeResult } from "./operators/extrude.ts";
export type { BevelOptions, BevelResult } from "./operators/bevel.ts";
export type { InsetOptions, InsetResult } from "./operators/inset.ts";
export type { EditableMesh as EditableMeshValue, EdgeView, ElementDomain, ElementSelection, ElementSet, FaceView, ScoredSelection, VertexView } from "./types.ts";
