export const meta = {
  slug: 'throwable-fluid',
  title: 'Throwable Fluid',
  description:
    'Throw a glass orb with Motion’s drag and inertia; it stirs a GPU fluid simulation and refracts the ink like a lens.',
  tags: [
    'motion',
    'fluid',
    'drag',
    'glass',
    'refraction',
    'navier-stokes',
    'chromatic-aberration',
    'simulation',
    'spring',
  ],
  capabilities: [
    'webgpu',
    'fragment-shader',
    'multi-pass',
    'render-targets',
    'textures',
    'external-ticker',
    'dom-overlay',
    'pointer-input',
    'controls',
    'select-control',
    'checkbox-controls',
    'responsive-canvas',
    'continuous-rendering',
    'resize',
  ],
  thumb: {
    warmupFrames: 1,
    dt: 1 / 60,
    time: 2,
  },
  files: [
    'index.tsx',
    'orb.tsx',
    'orb-store.ts',
    'renderer.ts',
    'orb-tracker.ts',
    'wake.ts',
    'pipeline.ts',
    'fluid.ts',
    'fluid-common.wgsl',
    'advect-velocity.wgsl',
    'curl.wgsl',
    'divergence.wgsl',
    'pressure.wgsl',
    'project.wgsl',
    'advect-dye.wgsl',
    'carry.wgsl',
    'composite.wgsl',
  ],
} as const;
