export const meta = {
  slug: 'throwable-fluid',
  title: 'Throwable Fluid',
  description:
    'A glass orb you can throw. The orb is a real, focusable DOM button that Motion drags: release it and Motion’s inertia coasts it with the tuned power and time constant, springs it back from past the walls, and scales it with hover and press springs. Every frame, inside Motion’s frameloop, vgpu reads the orb’s rect and steps a Navier–Stokes solver on half-float render targets: the orb drags the fluid along its whole swept path and lays luminous ink behind it, a wall impact throws the fluid back off the wall with a burst of ink, both scaled by the impact speed, and the orb itself is drawn as a glass lens that refracts the ink with chromatic dispersion, a Fresnel rim, a highlight and a soft shadow and caustic. Grab it, throw it, flick it with the arrow keys, or watch the idle flicks.',
  tags: [
    'motion',
    'fluid',
    'drag',
    'glass',
    'refraction',
    'navier-stokes',
    'chromatic-aberration',
    'simulation',
    'spring',
  ],
  capabilities: [
    'webgpu',
    'fragment-shader',
    'multi-pass',
    'render-targets',
    'textures',
    'external-ticker',
    'dom-overlay',
    'pointer-input',
    'controls',
    'select-control',
    'checkbox-controls',
    'responsive-canvas',
    'continuous-rendering',
    'resize',
  ],
  thumb: {
    warmupFrames: 1,
    dt: 1 / 60,
    time: 2,
  },
  files: [
    'index.tsx',
    'orb.tsx',
    'orb-store.ts',
    'renderer.ts',
    'orb-tracker.ts',
    'wake.ts',
    'pipeline.ts',
    'fluid.ts',
    'fluid-common.wgsl',
    'advect-velocity.wgsl',
    'curl.wgsl',
    'divergence.wgsl',
    'pressure.wgsl',
    'project.wgsl',
    'advect-dye.wgsl',
    'carry.wgsl',
    'composite.wgsl',
  ],
} as const;
