import { EXAMPLES_CONTRACT_ID,EXAMPLES_SCHEMA_SHA256 } from './contracts.js';
import { ExamplesCache } from './cache.js';
import { requestJson,requestBytes,LIMITS,trustedOrigin,assertTrustedUrl } from './http.js';
import { validateDiscovery,validatePointer,validateIndex,validateManifest } from './schema.js';
import { ExamplesError,integrity,network,notFound } from './errors.js';
import { sha256,aggregateSha256 } from './hashing.js';
import { assertUniquePaths } from './paths.js';
const JSON_TYPES=['application/json'];
const cmp=(a,b)=>{const parse=v=>{const m=String(v).match(/^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?(?:\+[0-9A-Za-z.-]+)?$/);if(!m)return;return {core:m.slice(1,4).map(Number),pre:m[4]?.split('.')};},pa=parse(a),pb=parse(b);if(!pa||!pb)return -1;for(let i=0;i<3;i++)if(pa.core[i]!==pb.core[i])return pa.core[i]-pb.core[i];if(!pa.pre)return pb.pre?1:0;if(!pb.pre)return -1;for(let i=0;i<Math.max(pa.pre.length,pb.pre.length);i++){const x=pa.pre[i],y=pb.pre[i];if(x===undefined)return -1;if(y===undefined)return 1;if(x===y)continue;const xn=/^\d+$/.test(x),yn=/^\d+$/.test(y);if(xn&&yn)return +x-+y;if(xn!==yn)return xn?-1:1;return x<y?-1:1}return 0};
export class ExamplesClient {
 constructor({baseUrl='https://vgpu.labs.vercel.dev',fetchImpl=fetch,cache=new ExamplesCache(),cliVersion='0.0.0',now=()=>new Date(),timeoutMs=10000,warn=()=>{}}={}){this.origin=trustedOrigin(baseUrl);this.fetchImpl=fetchImpl;this.cache=cache;this.cliVersion=cliVersion;this.now=now;this.timeoutMs=timeoutMs;this.warn=warn;}
 opts(limit,types=JSON_TYPES,extra={}){return {fetchImpl:this.fetchImpl,limit,contentTypes:types,timeoutMs:this.timeoutMs,...extra};}
 async handshake(){const path=this.cache.discoveryPath(),metaPath=this.cache.metaPath(),meta=await this.cache.readJson(metaPath)||{};const url=`${this.origin}/.well-known/vgpu-examples.json`;let r=await requestJson(url,this.opts(LIMITS.discovery,JSON_TYPES,{etag:meta.discoveryEtag}));let value;if(r.notModified){const bytes=await this.cache.read(path);if(!bytes)throw network('Discovery returned 304 without a cached response');try{value=JSON.parse(bytes)}catch{throw integrity('Corrupt cached discovery');}}else{value=r.value;}validateDiscovery(value);const contract=value.contracts.find(c=>c.id===EXAMPLES_CONTRACT_ID);if(!contract)throw new ExamplesError('VGPU-EXAMPLES-INCOMPATIBLE-API','No mutually supported examples API contract',5);if(contract.schemaSha256!==EXAMPLES_SCHEMA_SHA256)throw new ExamplesError('VGPU-EXAMPLES-INCOMPATIBLE-API','Server contract schema does not match this CLI',5);assertTrustedUrl(contract.indexUrl,this.origin);if(contract.status==='revoked')throw new ExamplesError('VGPU-EXAMPLES-INCOMPATIBLE-API','The v1 examples contract has been revoked',5);if(contract.status==='deprecated')this.warn('Warning: vgpu-examples/v1 is deprecated.\n');if(cmp(this.cliVersion,contract.minimumCliVersion)<0)throw new ExamplesError('VGPU-EXAMPLES-CLI-TOO-OLD',`CLI ${this.cliVersion} is older than required ${contract.minimumCliVersion}`,5);if(!r.notModified)await this.cache.write(path,r.bytes);await this.cache.write(metaPath,Buffer.from(JSON.stringify({...meta,discoveryEtag:r.etag??meta.discoveryEtag})+'\n'));return contract;}
 async getIndex({revision,offline=false}={}){if(offline){const meta=await this.cache.readJson(this.cache.metaPath())||{};const rev=revision||meta.latestRevision;if(!rev)throw network('No verified examples index is available offline');const bytes=await this.cache.read(this.cache.indexPath(rev));if(!bytes)throw network(`Revision ${rev} is not available offline`);let index;try{index=validateIndex(JSON.parse(bytes))}catch{throw integrity('Corrupt cached index');}if(index.revision!==rev)throw integrity('Cached index revision mismatch');const verified=await this.cache.readJson(this.cache.revisionMetaPath(rev));if(!verified?.lastVerifiedAt)throw network(`Revision ${rev} has not been verified`);if(verified.indexSha256!==sha256(bytes))throw integrity('Cached index SHA-256 mismatch');return {index,lastVerifiedAt:verified.lastVerifiedAt,offline:true};}
 const contract=await this.handshake();let rev=revision,indexUrl,expected;
 if(rev){if(!/^[a-f0-9]{64}$/.test(rev))throw integrity('Invalid revision SHA-256');const path=new URL(contract.indexUrl).pathname.startsWith('/api/')?`/api/examples/v1/revisions/${rev}/index.json`:`/examples/v1/revisions/${rev}/index.json`;indexUrl=`${this.origin}${path}`;}else{const pointerUrl=assertTrustedUrl(contract.indexUrl,this.origin);const p=await requestJson(pointerUrl,this.opts(LIMITS.index));validatePointer(p.value);rev=p.value.revision;expected=p.value.indexSha256;indexUrl=assertTrustedUrl(p.value.indexUrl,this.origin,rev);}
 const cached=await this.cache.read(this.cache.indexPath(rev));const r=await requestBytes(indexUrl,this.opts(LIMITS.index,JSON_TYPES,{etag:cached?`"${sha256(cached)}"`:undefined}));let bytes=r.notModified?cached:r.bytes;if(!bytes)throw network('Index returned 304 without a cached response');if(expected&&sha256(bytes)!==expected)throw integrity('Index SHA-256 mismatch');let index;try{index=validateIndex(JSON.parse(bytes))}catch(e){throw e instanceof ExamplesError?e:integrity('Invalid index');}if(index.revision!==rev)throw integrity('Index revision mismatch');if(!r.notModified)await this.cache.write(this.cache.indexPath(rev),bytes);await this.cache.mark(rev,sha256(bytes),this.now());const meta=await this.cache.readJson(this.cache.metaPath())||{};await this.cache.write(this.cache.metaPath(),Buffer.from(JSON.stringify({...meta,latestRevision:rev})+'\n'));return {index,lastVerifiedAt:this.now().toISOString(),offline:false};}
 find(index,id){const e=index.examples.find(x=>x.id===id);if(!e)throw notFound(`Example not found: ${id}`);return e;}
 async getManifest(index,id,{offline=false}={}){const entry=this.find(index,id),path=this.cache.manifestPath(index.revision,id);let bytes;if(offline)bytes=await this.cache.read(path);else{const url=assertTrustedUrl(entry.manifestUrl,this.origin,index.revision);const r=await requestBytes(url,this.opts(LIMITS.manifest));bytes=r.bytes;if(sha256(bytes)!==entry.manifestSha256)throw integrity('Manifest SHA-256 mismatch');}if(!bytes)throw network(`Manifest for ${id} is not available offline`);if(sha256(bytes)!==entry.manifestSha256)throw integrity('Cached manifest SHA-256 mismatch');const m=validateManifest(JSON.parse(bytes));if(m.id!==id||m.revision!==index.revision||m.aggregateSha256!==entry.aggregateSha256||m.files.length!==entry.fileCount)throw integrity('Manifest does not match index');assertUniquePaths(m.files);if(aggregateSha256(m)!==m.aggregateSha256)throw integrity('Manifest aggregate SHA-256 mismatch');if(!offline)await this.cache.write(path,bytes);return m;}
 async getFile(manifest,file,{offline=false}={}){const path=this.cache.filePath(manifest.revision,file.sha256);let bytes;if(offline)bytes=await this.cache.read(path);else{const url=assertTrustedUrl(file.url,this.origin,manifest.revision);const r=await requestBytes(url,this.opts(LIMITS.file,[file.contentType]));bytes=r.bytes;if(bytes.length!==file.size||sha256(bytes)!==file.sha256)throw integrity(`Source integrity mismatch: ${file.path}`);}if(!bytes)throw network(`Source file is not available offline: ${file.path}`);if(bytes.length!==file.size||sha256(bytes)!==file.sha256)throw integrity(`Cached source integrity mismatch: ${file.path}`);try{new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw integrity(`Source is not valid UTF-8: ${file.path}`);}if(!offline)await this.cache.write(path,bytes);return bytes;}
}
