import { constants,existsSync,renameSync,rmSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { mkdir,lstat,open,readFile,readdir,rename,rm,rmdir,writeFile } from 'node:fs/promises';
import { dirname,basename,parse,relative,resolve,join,sep } from 'node:path';
import { ExamplesError,destinationExists,filesystem,integrity } from './errors.js';
import { LIMITS } from './http.js';

const TOKEN=/^[a-f0-9]{32}$/;
const SELF_START=`${process.pid}:${Date.now()-Math.round(process.uptime()*1000)}`;
// Darwin O_NOFOLLOW_ANY rejects symlinks anywhere in a path; combining it with O_NOFOLLOW returns EINVAL.
const DARWIN_NOFOLLOW_ANY=process.platform==='darwin'?0x20000000:0;
async function exists(path){try{return await lstat(path)}catch(e){if(e.code==='ENOENT')return;throw e}}
function portablePath(path,platform){const full=resolve(path);if(platform!=='darwin'||process.platform!=='darwin')return full;for(const prefix of ['/tmp','/var','/etc'])if(full===prefix||full.startsWith(`${prefix}/`))return `/private${full}`;return full;}
async function portableParent(destination,platform){const output=resolve(destination),absolute=portablePath(output,platform),parent=dirname(absolute),root=parse(parent).root;let directory;try{let cursor=root;for(const part of relative(root,parent).split(sep).filter(Boolean)){cursor=join(cursor,part);let stat=await exists(cursor);if(!stat){try{await mkdir(cursor,{mode:0o700})}catch(e){if(e.code!=='EEXIST')throw e}stat=await lstat(cursor)}if(stat.isSymbolicLink()||!stat.isDirectory())throw filesystem(`Unsafe destination directory: ${cursor}`);const checked=await open(cursor,constants.O_RDONLY|constants.O_DIRECTORY|DARWIN_NOFOLLOW_ANY);await checked.close()}directory=await open(parent,constants.O_RDONLY|constants.O_DIRECTORY|DARWIN_NOFOLLOW_ANY);return {absolute,parent,output,portable:true,parentIdentity:identity(await directory.stat()),close:()=>directory.close()}}catch(e){await directory?.close().catch(()=>{});if(e?.code?.startsWith?.('VGPU-'))throw e;throw filesystem(`Unsafe destination parent: ${e.message}`)}}
async function safeParent(destination,platform=process.platform){if(platform==='darwin')return portableParent(destination,platform);if(platform!=='linux')throw filesystem(`Safe destination storage is unsupported on ${platform}`);const output=resolve(destination),root=parse(output).root,parts=relative(root,dirname(output)).split(sep).filter(Boolean);let directory;try{directory=await open(root,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);for(const part of parts){const child=`/proc/self/fd/${directory.fd}/${part}`;let next;try{next=await open(child,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW)}catch(e){if(e.code!=='ENOENT')throw e;try{await mkdir(child,{mode:0o700})}catch(mkdirError){if(mkdirError.code!=='EEXIST')throw mkdirError}next=await open(child,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW)}await directory.close();directory=next}const parent=`/proc/self/fd/${directory.fd}`;return {absolute:`${parent}/${basename(output)}`,parent,output,portable:false,close:()=>directory.close()}}catch(e){await directory?.close().catch(()=>{});throw filesystem(`Unsafe destination parent: ${e.message}`)}}
async function startTime(pid,platform){if(platform!=='linux'){if(pid===process.pid)return SELF_START;try{process.kill(pid,0);return 'alive'}catch(e){return e.code==='EPERM'?'alive':undefined}}try{const value=await readFile(`/proc/${pid}/stat`,'utf8'),tail=value.slice(value.lastIndexOf(')')+2).split(' ');return tail[19]}catch{return}}
const identity=s=>({dev:String(s.dev),ino:String(s.ino)});
const same=(s,id)=>!!s&&!!id&&!s.isSymbolicLink()&&String(s.dev)===id.dev&&String(s.ino)===id.ino;
async function assertParent(destination){if(destination.portable&&!same(await exists(destination.parent),destination.parentIdentity))throw filesystem('Destination parent identity changed');}
// This closes the staging window deterministically. Node has no portable rename-if-absent for
// directories, so the parent lock still only serializes cooperating VGPU writers; a hostile writer
// with access to the parent could race between this final check and rename().
async function assertDestinationUnclaimed(initial,destination,reported){if(!initial&&await exists(destination))throw destinationExists(`Destination already exists: ${reported}`);}
function names(name,token){return {temp:`.${name}.vgpu-tmp-${token}`,backup:`.${name}.vgpu-old-${token}`,stamp:`.${name}.vgpu-published-${token}`};}
function validOwner(value,name){if(!value||!TOKEN.test(value.token)||!Number.isInteger(value.pid)||typeof value.start!=='string')return false;const expected=names(name,value.token);return value.temp===expected.temp&&value.backup===expected.backup&&value.stamp===expected.stamp;}
async function readOwner(lock,name){try{const s=await lstat(join(lock,'owner'));if(s.isSymbolicLink()||!s.isFile())return;const value=JSON.parse(await readFile(join(lock,'owner'),'utf8'));return validOwner(value,name)?value:undefined}catch{return}}
async function active(owner,platform){const current=await startTime(owner.pid,platform);return platform==='linux'||owner.pid===process.pid?current===owner.start:current!==undefined;}
async function writeExclusive(path,bytes,portable){let handle;try{handle=await open(path,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|(portable?DARWIN_NOFOLLOW_ANY:constants.O_NOFOLLOW),0o600);await handle.writeFile(bytes);await handle.sync()}finally{await handle?.close()}}
async function writeOwner(lock,owner,portable){const path=join(lock,'owner'),tmp=join(lock,`.owner-${owner.token}`);await writeExclusive(tmp,Buffer.from(JSON.stringify(owner)+'\n'),portable);await rename(tmp,path);}
async function removeLock(lock,name,token){const owner=await readOwner(lock,name);if(!owner||owner.token!==token)return;const entries=await readdir(lock);if(entries.some(entry=>entry!=='owner'))throw filesystem('Unsafe destination lock contents');await rm(join(lock,'owner'));await rmdir(lock);}
async function acquire(lock,name,destination,platform,guard){let stale;const portable=platform==='darwin';for(let attempt=0;attempt<3;attempt++){const token=randomBytes(16).toString('hex'),owned=names(name,token),owner={pid:process.pid,start:await startTime(process.pid,platform),token,...owned,phase:'locked'};if(!owner.start)throw filesystem('Cannot determine process identity');try{await guard();await mkdir(lock,{mode:0o700});await guard();await writeExclusive(join(lock,'owner'),Buffer.from(JSON.stringify(owner)+'\n'),portable);return {owner,stale}}catch(e){if(e.code!=='EEXIST')throw filesystem(e.message);const s=await exists(lock);if(!s||s.isSymbolicLink()||!s.isDirectory())throw filesystem('Unsafe destination lock');const previous=await readOwner(lock,name);if(!previous)throw filesystem('Unauthenticated destination lock');if(await active(previous,platform))throw destinationExists(`Destination is busy: ${destination}`);const entries=await readdir(lock);if(entries.some(entry=>entry!=='owner'))throw filesystem('Unsafe stale destination lock');await rm(join(lock,'owner'));await rmdir(lock);stale=previous;}}throw filesystem('Cannot recover stale destination lock');}
async function ownedStamp(path,token){try{const s=await lstat(path);return s.isFile()&&!s.isSymbolicLink()&&(await readFile(path,'utf8'))===token}catch{return false}}
async function removeOwnedDirectory(path,id){const s=await exists(path);if(same(s,id)&&s.isDirectory())await rm(path,{recursive:true,force:true});}
async function writeStaged(root,path,parts,bytes,portable,beforeFileWrite){if(!portable){let directory=root,owned=false;try{for(const part of parts.slice(0,-1)){const child=`/proc/self/fd/${directory.fd}/${part}`;try{await mkdir(child,{mode:0o700})}catch(e){if(e.code!=='EEXIST')throw e}const next=await open(child,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);if(owned)await directory.close();directory=next;owned=true}const visible=join(path,...parts.slice(0,-1)),directoryIdentity=identity(await directory.stat());if(beforeFileWrite)await beforeFileWrite();await writeFile(`/proc/self/fd/${directory.fd}/${parts.at(-1)}`,bytes,{mode:0o600,flag:'wx'});if(!same(await exists(visible),directoryIdentity))throw filesystem('Staging directory identity changed');}finally{if(owned)await directory.close().catch(()=>{})}return}const rootIdentity=identity(await root.stat());if(!same(await exists(path),rootIdentity))throw filesystem('Staging directory identity changed');let directory=path;for(const part of parts.slice(0,-1)){directory=join(directory,part);try{await mkdir(directory,{mode:0o700})}catch(e){if(e.code!=='EEXIST')throw e}const stat=await lstat(directory);if(stat.isSymbolicLink()||!stat.isDirectory())throw filesystem(`Unsafe staging directory: ${part}`);const checked=await open(directory,constants.O_RDONLY|constants.O_DIRECTORY|DARWIN_NOFOLLOW_ANY);await checked.close();if(!same(await exists(path),rootIdentity))throw filesystem('Staging directory identity changed')}const directoryIdentity=identity(await lstat(directory));if(beforeFileWrite)await beforeFileWrite();await writeExclusive(join(directory,parts.at(-1)),bytes,true);if(!same(await exists(directory),directoryIdentity)||!same(await exists(path),rootIdentity))throw filesystem('Staging directory identity changed');}
async function recover(parent,name,absolute,owner){if(!owner)return;const temp=join(parent,owner.temp),backup=join(parent,owner.backup),stamp=join(parent,owner.stamp),old=await exists(backup),current=await exists(absolute);if(old){if(!same(old,owner.backupIdentity)||!old.isDirectory())throw filesystem('Unauthenticated stale pull backup');const published=owner.phase==='published'&&current?.isDirectory()&&!current.isSymbolicLink()&&await ownedStamp(stamp,owner.token);if(published){await rm(backup,{recursive:true});await rm(stamp,{force:true});}else{if(current){const quarantine=join(parent,`.${name}.vgpu-rejected-${randomBytes(16).toString('hex')}`);await rename(absolute,quarantine);}await rename(backup,absolute);await rm(stamp,{force:true});}}await removeOwnedDirectory(temp,owner.tempIdentity);}
function guardSignals(restore){let handled=false;const handlers={SIGINT:()=>handle('SIGINT'),SIGTERM:()=>handle('SIGTERM')},close=()=>{for(const [signal,handler] of Object.entries(handlers))process.off(signal,handler);},handle=signal=>{if(handled)return;handled=true;close();try{restore()}finally{process.kill(process.pid,signal)}};for(const [signal,handler] of Object.entries(handlers))process.once(signal,handler);return close;}

export async function pullExample(client,manifest,destination,{force=false,offline=false,beforeFileWrite,beforePublish,afterBackupRename,afterPublish,platform=process.platform,signal}={}){
 signal?.throwIfAborted();
 const total=manifest.files.reduce((n,f)=>n+f.size,0);if(total>LIMITS.pull)throw integrity('Example exceeds 32 MiB pull limit');
 const safeDestination=await safeParent(destination,platform),guard=()=>assertParent(safeDestination),{absolute,parent,output}=safeDestination,name=basename(output),lock=join(parent,`.${name}.vgpu.lock`);let acquired;try{acquired=await acquire(lock,name,destination,platform,guard)}catch(e){await safeDestination.close().catch(()=>{});throw e}const owner=acquired.owner,temp=join(parent,owner.temp),backup=join(parent,owner.backup),stamp=join(parent,owner.stamp);
 let moved=false,published=false,stage;
 try{
  await guard();
  await recover(parent,name,absolute,acquired.stale);
  const current=await exists(absolute);if(current&&!force)throw destinationExists(`Destination already exists: ${destination}`);if(current&&(current.isSymbolicLink()||!current.isDirectory()))throw filesystem('Destination must be a real directory');
  await guard();await mkdir(temp,{mode:0o700});stage=await open(temp,constants.O_RDONLY|constants.O_DIRECTORY|(safeDestination.portable?DARWIN_NOFOLLOW_ANY:constants.O_NOFOLLOW));owner.tempIdentity=identity(await stage.stat());owner.phase='staging';await writeOwner(lock,owner,safeDestination.portable);
  let next=0;async function worker(){while(true){signal?.throwIfAborted();const i=next++;if(i>=manifest.files.length)return;const file=manifest.files[i],bytes=await client.getFile(manifest,file,{offline,signal});signal?.throwIfAborted();await writeStaged(stage,temp,file.path.split('/'),bytes,safeDestination.portable,beforeFileWrite);}}
  await Promise.all(Array.from({length:Math.min(4,manifest.files.length)},worker));
  const unguard=guardSignals(()=>{if(!published&&existsSync(backup)&&!existsSync(absolute)){try{renameSync(backup,absolute)}catch{}moved=false;}try{rmSync(temp,{recursive:true,force:true})}catch{}try{rmSync(lock,{recursive:true,force:true})}catch{}});
  try{if(current){await guard();owner.backupIdentity=identity(current);owner.phase='backup-planned';await writeOwner(lock,owner,safeDestination.portable);await rename(absolute,backup);moved=true;if(afterBackupRename)await afterBackupRename();if(!same(await lstat(backup),owner.backupIdentity))throw filesystem('Pull backup identity changed');owner.phase='backed-up';await writeOwner(lock,owner,safeDestination.portable);}if(beforePublish)await beforePublish();await guard();if(!same(await stage.stat(),owner.tempIdentity)||!same(await exists(temp),owner.tempIdentity))throw filesystem('Staging directory identity changed');await assertDestinationUnclaimed(current,absolute,destination);signal?.throwIfAborted();await rename(temp,absolute);if(!same(await exists(absolute),owner.tempIdentity)){const rejected=join(parent,`.${name}.vgpu-rejected-${randomBytes(16).toString('hex')}`);await rename(absolute,rejected).catch(()=>{});throw filesystem('Published staging identity changed')}published=true;moved=false;await writeExclusive(stamp,Buffer.from(owner.token),safeDestination.portable);owner.phase='published';await writeOwner(lock,owner,safeDestination.portable);}finally{unguard()}
  if(afterPublish)await afterPublish();
  if(await exists(backup)){const old=await exists(backup);if(!same(old,owner.backupIdentity))throw filesystem('Pull backup identity changed');await rm(backup,{recursive:true});}await rm(stamp,{force:true});
  return {out:output,files:manifest.files.length,bytes:total};
 }catch(e){if(moved&&!published)await rename(backup,absolute).catch(()=>{});else if(published)await recover(parent,name,absolute,owner).catch(()=>{});if(e instanceof ExamplesError||e?.name==='AbortError'||signal?.aborted&&e===signal.reason)throw e;throw filesystem(`Pull failed: ${e.message}`);
 }finally{await stage?.close().catch(()=>{});await removeOwnedDirectory(temp,owner.tempIdentity).catch(()=>{});await removeLock(lock,name,owner.token).catch(()=>{});await safeDestination.close().catch(()=>{});}
}
