import { constants,existsSync,renameSync,rmSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { mkdir,lstat,open,readFile,readdir,rename,rm,rmdir,writeFile } from 'node:fs/promises';
import { dirname,basename,parse,relative,resolve,join,sep } from 'node:path';
import { ExamplesError,filesystem,integrity } from './errors.js';
import { LIMITS } from './http.js';

const TOKEN=/^[a-f0-9]{32}$/;
async function exists(path){try{return await lstat(path)}catch(e){if(e.code==='ENOENT')return;throw e}}
async function safeParent(destination){if(process.platform!=='linux')throw filesystem(`Safe destination storage is unsupported on ${process.platform}`);const output=resolve(destination),root=parse(output).root,parts=relative(root,dirname(output)).split(sep).filter(Boolean);let directory;try{directory=await open(root,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);for(const part of parts){const child=`/proc/self/fd/${directory.fd}/${part}`;let next;try{next=await open(child,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW)}catch(e){if(e.code!=='ENOENT')throw e;try{await mkdir(child,{mode:0o700})}catch(mkdirError){if(mkdirError.code!=='EEXIST')throw mkdirError}next=await open(child,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW)}await directory.close();directory=next}const parent=`/proc/self/fd/${directory.fd}`;return {absolute:`${parent}/${basename(output)}`,parent,output,close:()=>directory.close()}}catch(e){await directory?.close().catch(()=>{});throw filesystem(`Unsafe destination parent: ${e.message}`)}}
async function startTime(pid){try{const value=await readFile(`/proc/${pid}/stat`,'utf8'),tail=value.slice(value.lastIndexOf(')')+2).split(' ');return tail[19]}catch{return}}
const identity=s=>({dev:String(s.dev),ino:String(s.ino)});
const same=(s,id)=>!!s&&!!id&&!s.isSymbolicLink()&&String(s.dev)===id.dev&&String(s.ino)===id.ino;
function names(name,token){return {temp:`.${name}.vgpu-tmp-${token}`,backup:`.${name}.vgpu-old-${token}`,stamp:`.${name}.vgpu-published-${token}`};}
function validOwner(value,name){if(!value||!TOKEN.test(value.token)||!Number.isInteger(value.pid)||typeof value.start!=='string')return false;const expected=names(name,value.token);return value.temp===expected.temp&&value.backup===expected.backup&&value.stamp===expected.stamp;}
async function readOwner(lock,name){try{const s=await lstat(join(lock,'owner'));if(s.isSymbolicLink()||!s.isFile())return;const value=JSON.parse(await readFile(join(lock,'owner'),'utf8'));return validOwner(value,name)?value:undefined}catch{return}}
async function active(owner){return (await startTime(owner.pid))===owner.start;}
async function writeOwner(lock,owner){const path=join(lock,'owner'),tmp=join(lock,`.owner-${owner.token}`);await writeFile(tmp,JSON.stringify(owner)+'\n',{mode:0o600,flag:'wx'});await rename(tmp,path);}
async function removeLock(lock,name,token){const owner=await readOwner(lock,name);if(!owner||owner.token!==token)return;const entries=await readdir(lock);if(entries.some(entry=>entry!=='owner'))throw filesystem('Unsafe destination lock contents');await rm(join(lock,'owner'));await rmdir(lock);}
async function acquire(lock,name,destination){let stale;for(let attempt=0;attempt<3;attempt++){const token=randomBytes(16).toString('hex'),owned=names(name,token),owner={pid:process.pid,start:await startTime(process.pid),token,...owned,phase:'locked'};if(!owner.start)throw filesystem('Cannot determine process identity');try{await mkdir(lock,{mode:0o700});await writeFile(join(lock,'owner'),JSON.stringify(owner)+'\n',{mode:0o600,flag:'wx'});return {owner,stale}}catch(e){if(e.code!=='EEXIST')throw filesystem(e.message);const s=await exists(lock);if(!s||s.isSymbolicLink()||!s.isDirectory())throw filesystem('Unsafe destination lock');const previous=await readOwner(lock,name);if(!previous)throw filesystem('Unauthenticated destination lock');if(await active(previous))throw new ExamplesError('VGPU-EXAMPLES-DESTINATION-EXISTS',`Destination is busy: ${destination}`,6);const entries=await readdir(lock);if(entries.some(entry=>entry!=='owner'))throw filesystem('Unsafe stale destination lock');await rm(join(lock,'owner'));await rmdir(lock);stale=previous;}}throw filesystem('Cannot recover stale destination lock');}
async function ownedStamp(path,token){try{const s=await lstat(path);return s.isFile()&&!s.isSymbolicLink()&&(await readFile(path,'utf8'))===token}catch{return false}}
async function removeOwnedDirectory(path,id){const s=await exists(path);if(same(s,id)&&s.isDirectory())await rm(path,{recursive:true,force:true});}
async function writeStaged(root,parts,bytes){let directory=root,owned=false;try{for(const part of parts.slice(0,-1)){const child=`/proc/self/fd/${directory.fd}/${part}`;try{await mkdir(child,{mode:0o700})}catch(e){if(e.code!=='EEXIST')throw e}const next=await open(child,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);if(owned)await directory.close();directory=next;owned=true}await writeFile(`/proc/self/fd/${directory.fd}/${parts.at(-1)}`,bytes,{mode:0o600,flag:'wx'});}finally{if(owned)await directory.close().catch(()=>{})}}
async function recover(parent,name,absolute,owner){if(!owner)return;const temp=join(parent,owner.temp),backup=join(parent,owner.backup),stamp=join(parent,owner.stamp),old=await exists(backup),current=await exists(absolute);if(old){if(!same(old,owner.backupIdentity)||!old.isDirectory())throw filesystem('Unauthenticated stale pull backup');const published=owner.phase==='published'&&current?.isDirectory()&&!current.isSymbolicLink()&&await ownedStamp(stamp,owner.token);if(published){await rm(backup,{recursive:true});await rm(stamp,{force:true});}else{if(current){const quarantine=join(parent,`.${name}.vgpu-rejected-${randomBytes(16).toString('hex')}`);await rename(absolute,quarantine);}await rename(backup,absolute);await rm(stamp,{force:true});}}await removeOwnedDirectory(temp,owner.tempIdentity);}
function guardSignals(restore){let handled=false;const handlers={SIGINT:()=>handle('SIGINT'),SIGTERM:()=>handle('SIGTERM')},close=()=>{for(const [signal,handler] of Object.entries(handlers))process.off(signal,handler);},handle=signal=>{if(handled)return;handled=true;close();try{restore()}finally{process.kill(process.pid,signal)}};for(const [signal,handler] of Object.entries(handlers))process.once(signal,handler);return close;}

export async function pullExample(client,manifest,destination,{force=false,offline=false,beforePublish,afterBackupRename,afterPublish}={}){
 const total=manifest.files.reduce((n,f)=>n+f.size,0);if(total>LIMITS.pull)throw integrity('Example exceeds 32 MiB pull limit');
 const safeDestination=await safeParent(destination),{absolute,parent,output}=safeDestination,name=basename(output),lock=join(parent,`.${name}.vgpu.lock`);let acquired;try{acquired=await acquire(lock,name,destination)}catch(e){await safeDestination.close().catch(()=>{});throw e}const owner=acquired.owner,temp=join(parent,owner.temp),backup=join(parent,owner.backup),stamp=join(parent,owner.stamp);
 let moved=false,published=false,stage;
 try{
  await recover(parent,name,absolute,acquired.stale);
  const current=await exists(absolute);if(current&&!force)throw new ExamplesError('VGPU-EXAMPLES-DESTINATION-EXISTS',`Destination already exists: ${destination}`,6);if(current&&(current.isSymbolicLink()||!current.isDirectory()))throw filesystem('Destination must be a real directory');
  await mkdir(temp,{mode:0o700});stage=await open(temp,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);owner.tempIdentity=identity(await stage.stat());owner.phase='staging';await writeOwner(lock,owner);
  let next=0;async function worker(){while(true){const i=next++;if(i>=manifest.files.length)return;const file=manifest.files[i],bytes=await client.getFile(manifest,file,{offline});await writeStaged(stage,file.path.split('/'),bytes);}}
  await Promise.all(Array.from({length:Math.min(4,manifest.files.length)},worker));
  const unguard=guardSignals(()=>{if(!published&&existsSync(backup)&&!existsSync(absolute)){try{renameSync(backup,absolute)}catch{}moved=false;}try{rmSync(temp,{recursive:true,force:true})}catch{}try{rmSync(lock,{recursive:true,force:true})}catch{}});
  try{if(current){owner.backupIdentity=identity(current);owner.phase='backup-planned';await writeOwner(lock,owner);await rename(absolute,backup);moved=true;if(afterBackupRename)await afterBackupRename();if(!same(await lstat(backup),owner.backupIdentity))throw filesystem('Pull backup identity changed');owner.phase='backed-up';await writeOwner(lock,owner);}if(beforePublish)await beforePublish();if(!same(await stage.stat(),owner.tempIdentity)||!same(await exists(temp),owner.tempIdentity))throw filesystem('Staging directory identity changed');await rename(temp,absolute);if(!same(await exists(absolute),owner.tempIdentity)){const rejected=join(parent,`.${name}.vgpu-rejected-${randomBytes(16).toString('hex')}`);await rename(absolute,rejected).catch(()=>{});throw filesystem('Published staging identity changed')}published=true;moved=false;await writeFile(stamp,owner.token,{mode:0o600,flag:'wx'});owner.phase='published';await writeOwner(lock,owner);}finally{unguard()}
  if(afterPublish)await afterPublish();
  if(await exists(backup)){const old=await exists(backup);if(!same(old,owner.backupIdentity))throw filesystem('Pull backup identity changed');await rm(backup,{recursive:true});}await rm(stamp,{force:true});
  return {out:output,files:manifest.files.length,bytes:total};
 }catch(e){if(moved&&!published)await rename(backup,absolute).catch(()=>{});else if(published)await recover(parent,name,absolute,owner).catch(()=>{});if(e instanceof ExamplesError)throw e;throw filesystem(`Pull failed: ${e.message}`);
 }finally{await stage?.close().catch(()=>{});await removeOwnedDirectory(temp,owner.tempIdentity).catch(()=>{});await removeLock(lock,name,owner.token).catch(()=>{});await safeDestination.close().catch(()=>{});}
}
