import { examplesHelp } from './help.js';
import { ExamplesClient } from './client.js';
import { ExamplesCache,cacheRoot } from './cache.js';
import { searchExamples,tokens } from './search.js';
import { pullExample } from './pull.js';
import { errorResult,usage,notFound } from './errors.js';
import { assertSafeRelativePath } from './paths.js';
const SHA=/^[a-f0-9]{64}$/;
const json=(value,pretty)=>JSON.stringify(value,null,pretty?2:0)+'\n';
function parse(command,args){const positional=[],o={};const allowed={search:new Set(['any','limit','revision','offline','pretty','base-url']),show:new Set(['revision','offline','pretty','base-url']),cat:new Set(['revision','offline','json','base-url']),pull:new Set(['out','revision','offline','force','pretty','base-url'])}[command];if(!allowed)throw usage(`Unknown examples command: ${command}`);for(let i=0;i<args.length;i++){const a=args[i];if(!a.startsWith('--')){positional.push(a);continue}const key=a.slice(2);if(!allowed.has(key)||Object.hasOwn(o,key))throw usage(`Invalid or duplicate option: ${a}`);if(['limit','revision','out','base-url'].includes(key)){if(!args[i+1]||args[i+1].startsWith('--'))throw usage(`Option ${a} requires a value`);o[key]=args[++i]}else o[key]=true;}return {positional,o};}
export async function runExamples(args,{version='0.0.0',env=process.env,fetchImpl=fetch,now=()=>new Date()}={}){
 let warnings='';try{const [command,...rest]=args;if(command===undefined||command==='help'||command==='--help'||command==='-h')return {code:0,stdout:examplesHelp};if(command==='cache'){if(rest.length!==1||!['path','clear'].includes(rest[0]))throw usage('Usage: vgpu examples cache path|clear');const cache=new ExamplesCache(cacheRoot(env));if(rest[0]==='path')return {code:0,stdout:`${cache.root}\n`};await cache.clear();return {code:0,stdout:json({cleared:true,path:cache.root},false)}}const {positional,o}=parse(command,rest);const counts={search:1,show:1,cat:2,pull:1};if(positional.length!==counts[command])throw usage(`Invalid arguments for examples ${command}`);if(o.revision&&!SHA.test(o.revision))throw usage('--revision must be a lowercase SHA-256');if(o.limit!==undefined&&(!/^\d+$/.test(o.limit)||+o.limit<1||+o.limit>100))throw usage('--limit must be an integer from 1 to 100');if(command==='pull'&&!o.out)throw usage('pull requires --out <directory>');if(command==='search'&&!tokens(positional[0]).length)throw usage('Search query must contain a letter or number');const client=new ExamplesClient({baseUrl:o['base-url']||env.VGPU_EXAMPLES_BASE_URL||'https://vgpu.labs.vercel.dev',fetchImpl,cache:new ExamplesCache(cacheRoot(env)),cliVersion:version,now,warn:x=>warnings+=x});const state=await client.getIndex({revision:o.revision,offline:!!o.offline});let value;
 if(command==='search'){value={revision:state.index.revision,results:searchExamples(state.index,positional[0],{any:!!o.any,limit:o.limit?+o.limit:20}),...(state.offline?{lastVerifiedAt:state.lastVerifiedAt}:{})};}
 if(command==='show'){const manifest=await client.getManifest(state.index,positional[0],{offline:!!o.offline});value={...manifest,...(state.offline?{lastVerifiedAt:state.lastVerifiedAt}:{})};}
 if(command==='cat'){const manifest=await client.getManifest(state.index,positional[0],{offline:!!o.offline}),path=assertSafeRelativePath(positional[1]),file=manifest.files.find(f=>f.path===path);if(!file)throw notFound(`File not found: ${path}`);const bytes=await client.getFile(manifest,file,{offline:!!o.offline});if(!o.json)return {code:0,stdout:bytes,...(warnings?{stderr:warnings}:{})};value={revision:manifest.revision,id:manifest.id,path:file.path,content:bytes.toString('utf8'),size:file.size,sha256:file.sha256};}
 if(command==='pull'){const manifest=await client.getManifest(state.index,positional[0],{offline:!!o.offline}),result=await pullExample(client,manifest,o.out,{force:!!o.force,offline:!!o.offline});value={revision:manifest.revision,id:manifest.id,...result,aggregateSha256:manifest.aggregateSha256,...(state.offline?{lastVerifiedAt:state.lastVerifiedAt}:{})};}
 return {code:0,stdout:json(value,!!o.pretty),...(warnings?{stderr:warnings}:{})};}catch(e){return errorResult(e)}
}
