import { integrity } from './errors.js';
const SHA=/^[a-f0-9]{64}$/; const ID=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const exact=(o, keys, name)=>{ if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!keys.includes(k))) throw integrity(`Invalid ${name} schema`); };
const str=(v)=>typeof v==='string';
const nonempty=(v)=>str(v)&&v.length>0;
const strings=(v)=>Array.isArray(v)&&v.every(str)&&new Set(v).size===v.length;
const uri=(v)=>{if(!str(v))return false;try{new URL(v);return true}catch{return false}};
export function validateDiscovery(d){ exact(d,['protocol','discoveryVersion','contracts'],'discovery'); if(d.protocol!=='vgpu-examples'||d.discoveryVersion!==1||!Array.isArray(d.contracts)||!d.contracts.length) throw integrity('Invalid discovery schema'); const ids=new Set;for(const c of d.contracts){exact(c,['id','schemaSha256','status','minimumCliVersion','indexUrl'],'discovery contract'); if(!/^vgpu-examples\/v[1-9]\d*$/.test(c.id)||ids.has(c.id)||!SHA.test(c.schemaSha256)||!['active','deprecated','revoked'].includes(c.status)||!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/.test(c.minimumCliVersion)||!uri(c.indexUrl)) throw integrity('Invalid discovery contract');ids.add(c.id);} return d; }
export function validatePointer(p){exact(p,['schemaVersion','contractId','revision','indexUrl','indexSha256'],'latest pointer'); if(p.schemaVersion!==1||p.contractId!=='vgpu-examples/v1'||!SHA.test(p.revision)||!SHA.test(p.indexSha256)||!uri(p.indexUrl)) throw integrity('Invalid latest pointer'); return p;}
const validateExample=(e)=>{exact(e,['id','title','description','tags','capabilities','fileCount','aggregateSha256','manifestUrl','manifestSha256'],'index example'); if(!ID.test(e.id)||!nonempty(e.title)||!nonempty(e.description)||!uri(e.manifestUrl)||!strings(e.tags)||!strings(e.capabilities)||!Number.isInteger(e.fileCount)||e.fileCount<1||e.fileCount>128||!SHA.test(e.aggregateSha256)||!SHA.test(e.manifestSha256)) throw integrity('Invalid index example');};
export function validateIndex(i){exact(i,['schemaVersion','contractId','revision','source','examples'],'index'); if(i.schemaVersion!==1||i.contractId!=='vgpu-examples/v1'||!SHA.test(i.revision)||!i.source||Object.keys(i.source).sort().join()!=['gitCommit','repository'].join()||!nonempty(i.source.repository)||!nonempty(i.source.gitCommit)||!Array.isArray(i.examples)) throw integrity('Invalid index schema'); i.examples.forEach(validateExample); return i;}
export function validateManifest(m){exact(m,['schemaVersion','contractId','revision','id','title','description','tags','capabilities','aggregateSha256','files'],'manifest'); if(m.schemaVersion!==1||m.contractId!=='vgpu-examples/v1'||!SHA.test(m.revision)||!ID.test(m.id)||!nonempty(m.title)||!nonempty(m.description)||!strings(m.tags)||!strings(m.capabilities)||!SHA.test(m.aggregateSha256)||!Array.isArray(m.files)||m.files.length<1||m.files.length>128) throw integrity('Invalid manifest schema'); for(const f of m.files){exact(f,['path','contentType','size','sha256','url'],'manifest file'); if(!str(f.path)||!['text/typescript','text/wgsl','text/plain'].includes(f.contentType)||!Number.isInteger(f.size)||f.size<0||f.size>2097152||!SHA.test(f.sha256)||!uri(f.url)) throw integrity('Invalid manifest file');} return m;}
