// subharness tool: run an example's whole pre-commit checklist in one call and report each check.
import { access, readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { tool } from "subharness";
import { z } from "zod";
import { runCommand } from "./run.ts";
import { lintWgslCompat } from "./wgsl-compat-lint.ts";

export const verifyExampleTool = tool({
  description: [
    "Run the example's pre-commit checklist and report pass/fail per check with the failing output tail:",
    "a WGSL compatibility-mode lint of the example's shaders (flat/linear/sample interpolation, sample builtins, cube arrays, textureLoad on depth, sine hashes — CI's Mesa renderer rejects what Metal accepts),",
    "focused vitest (the example + foundation/actions/vocabulary tests), import boundaries, vocabulary, kebab-case filenames, apps/docs typecheck (needs types generated by a prior dev/build run),",
    "generated sources in sync (it re-runs ingest-examples.mjs, which rewrites examples-source/example-thumbs.generated.ts — commit what it changes), budget entry and both thumbnail PNGs present,",
    "and working-tree hygiene (next-env.d.ts / apps/docs/agents.md churn from next build/dev must not be committed). Takes 10–20 s. It does not run the production build or the Mesa thumbnail check.",
  ].join(" "),
  inputSchema: z.object({
    slug: z.string().regex(/^[a-z0-9-]+$/),
    typecheck: z.boolean().optional().describe("Run `tsc --noEmit` in apps/docs (default true)."),
  }),
  execute: async ({ slug, typecheck = true }) => {
    const root = process.cwd();
    const docs = path.join(root, "apps/docs");
    const commands: [string, string, string][] = [
      ["vitest", `pnpm exec vitest run apps/docs/examples/${slug} apps/docs/lib/example-foundation.test.ts apps/docs/lib/example-actions.test.ts apps/docs/scripts/validate-example-vocabulary.test.ts`, root],
      ["imports", "node apps/docs/scripts/check-example-imports.mjs", root],
      ["vocabulary", "node apps/docs/scripts/validate-example-vocabulary.mjs", root],
      ["filenames", "pnpm check:filenames", root],
      ...(typecheck ? [["typecheck", "pnpm exec tsc --noEmit", docs] as [string, string, string]] : []),
      ["ingest", "node scripts/ingest-examples.mjs", docs],
    ];
    const checks: Record<string, unknown>[] = [];
    const exampleDir = path.join(docs, "examples", slug);
    const shaders = (await readdir(exampleDir, { recursive: true })).filter((file) => String(file).endsWith(".wgsl")).map(String);
    const lint = lintWgslCompat(await Promise.all(shaders.map(async (file) => ({ file, source: await readFile(path.join(exampleDir, file), "utf8") }))));
    checks.push({ check: "wgsl-compat-lint", ok: lint.length === 0, ...(lint.length ? { findings: lint } : { note: `${shaders.length} shaders clean` }) });
    for (const [name, command, cwd] of commands) {
      const result = await runCommand(command, cwd, { tailLines: 30, timeoutMs: 240_000 });
      checks.push({ check: name, ok: result.code === 0, seconds: result.seconds, ...(result.code === 0 ? {} : { output: result.output }) });
    }
    const generated = await runCommand("git status --porcelain apps/docs/lib/examples-source.generated.ts apps/docs/lib/example-thumbs.generated.ts", root);
    checks.push({ check: "generated-files", ok: true, note: generated.output.trim() ? `ingest updated: ${generated.output.trim()} — include in the commit` : "unchanged vs index/HEAD" });
    const budgets = JSON.parse(await readFile(path.join(docs, "scripts/example-chunk-budgets.json"), "utf8"));
    checks.push({ check: "budget-entry", ok: typeof budgets.examples?.[slug] === "number", note: budgets.examples?.[slug] ?? "missing — use bundle_report after a production build" });
    const thumbs = await Promise.all(["card", "hero"].map((kind) => access(path.join(docs, "public/examples", `${slug}.${kind}.png`)).then(() => true, () => false)));
    checks.push({ check: "thumbnails", ok: thumbs.every(Boolean), note: thumbs.every(Boolean) ? "card + hero present" : "missing — node .subharness/tools/thumbs/mesa.ts <slug> --update" });
    const churn = await runCommand("git status --porcelain apps/docs/next-env.d.ts apps/docs/agents.md", root);
    checks.push({ check: "tree-hygiene", ok: !churn.output.trim(), note: churn.output.trim() ? `revert before committing: ${churn.output.trim()} (git checkout -- <file>)` : "clean" });
    return JSON.parse(JSON.stringify({ ok: checks.every((check) => check.ok), checks }));
  },
});
