export const meta = {
  slug: "transmission",
  title: "Transmission",
  description:
    "A glass cube refracts the scene behind it in screen space: the frame is rendered, blurred into a pyramid, and read back through Snell refraction, chromatic dispersion and a Fresnel-weighted environment reflection.",
  tags: ["lighting", "hdr", "rendering", "shader"],
  capabilities: [
    "webgpu",
    "pointer-orbit",
    "controls",
    "checkbox-controls",
    "select-control",
    "multi-pass",
    "render-targets",
    "continuous-rendering",
    "responsive-canvas",
    "textures",
    "hdr",
  ],
  thumb: { warmupFrames: 3 },
  files: [
    "index.tsx",
    "renderer.ts",
    "scene.ts",
    "camera.ts",
    "pointer-input.ts",
    "sky.wgsl",
    "blur.wgsl",
    "env-common.wgsl",
    "scene-background.wgsl",
    "floor.wgsl",
    "glass.wgsl",
    "present.wgsl",
  ],
} as const;
