export const meta = {
  slug: "fluid",
  title: "Interactive Fluid",
  description:
    "A compact pressure-projected fluid solver with velocity advection, colorful dye, and pointer or touch stirring.",
  tags: ["fluid", "simulation", "compute", "navier-stokes"],
  capabilities: [
    "webgpu",
    "compute-shader",
    "fixed-timestep",
    "pointer-input",
    "multi-pass",
    "responsive-canvas",
  ],
  thumb: { warmupFrames: 120 },
  files: [
    "index.tsx",
    "renderer.ts",
    "pointer-input.ts",
    "simulation.ts",
    "fluid-common.wgsl",
    "advect-velocity.wgsl",
    "curl.wgsl",
    "vorticity.wgsl",
    "divergence.wgsl",
    "pressure.wgsl",
    "project.wgsl",
    "advect-dye.wgsl",
    "display.wgsl",
  ],
} as const;
