export const meta = {
  slug: "radiance-cascades",
  title: "Radiance Cascades",
  description:
    "Draw light with the pointer and watch it bounce: a jump-flooded distance field feeds six radiance cascades — base 4, geometric intervals, linear RGBA16F — merged top-down with visibility alpha into 2D global illumination.",
  tags: ["lighting", "hdr", "raymarching", "rendering", "shader"],
  capabilities: [
    "webgpu",
    "multi-pass",
    "render-targets",
    "textures",
    "hdr",
    "pointer-input",
    "controls",
    "select-control",
    "responsive-canvas",
    "continuous-rendering",
  ],
  thumb: { warmupFrames: 1 },
  files: [
    "index.tsx",
    "renderer.ts",
    "simulation.ts",
    "pointer-input.ts",
    "rc-directions.wgsl",
    "sdf-sample.wgsl",
    "paint-emitter.wgsl",
    "jfa-init.wgsl",
    "jfa-pass.wgsl",
    "sdf-finalize.wgsl",
    "radiance-cascade.wgsl",
    "present.wgsl",
  ],
} as const;
